-- GENERATED by tools/gen_sewers.py -- do not edit. Knox County: the squares, by chunk.
if isClient() then return end
SEW = SEW or {}
SEW.Data = SEW.Data or {}
local T = { id = "knox_county_2", name = "Knox County", chunks = {}, furniture = {}, claimed = {} }
SEW.Data["knox_county_2"] = T
local c, f, z = T.chunks, T.furniture, T.claimed
c["1878,101"]="76scc..77s.c.."
c["1878,102"]="70s.c..71s.c..72s.c..73rc..."
c["1879,101"]="06sc...07s....16sc...17s....26sc...27s....36sc...37s....46r.c..47r.c.."
c["1879,102"]="00s....01s....02s....03tcc..04t.c..05t.c..06rc...10s....11s....12s....13tc..h14gc.Lx15t....16rc...20s....21s....22s....23td...24t...v25t....26rc.P.30s....31s....32s....33rccP.34r.c..35r.c..40r.c..41r.c..42r.c.."
f["1878,101"]={{15031,814,"carpentry_01_16","fuel",nil}}
f["1879,101"]={{15033,814,"constructedobjects_01_46","mechanic","j93"},{15035,814,"carpentry_02_64","hardware",nil}}
return T
