-- GENERATED by tools/gen_sewers.py -- do not edit. Knox County: the squares, by chunk.
if isClient() then return end
SEW = SEW or {}
SEW.Data = SEW.Data or {}
local T = { id = "knox_county", name = "Knox County", chunks = {}, furniture = {}, claimed = {}, caveFurniture = {}, caveClaimed = {} }
SEW.Data["knox_county"] = T
local c, f, z, v, u = T.chunks, T.furniture, T.claimed, T.caveFurniture, T.caveClaimed
c["1260,835"]="44scc..45s.c..46s.c..47s.c..51tcc..52t.c.e53t.c.e54sc...55s....56s....57s....61tc...62gc.Lx63t....64sc...65s....66s....67s....71tc..e72t....73t...v74sd...75s....76s....77s...."
c["1260,836"]="40s.c..41s.c..42rc...50s....51s....52rc...60s....61s....62rc...70s....71s....72rc..."
c["1261,835"]="01r.c..02r.c..03r.c..04sc...05s....06s....07s....14r.c..15r.c..16r.c..17r.c.."
c["1261,836"]="00s....01s....02rc.P.10r.c..11r.c.."
f["1260,836"]={{10086,6689,"constructedobjects_01_44","mechanic","j91"},{10084,6689,"carpentry_01_16","fuel",nil}}
f["1261,836"]={{10088,6689,"carpentry_02_67","hardware",nil}}
return T
