-- GENERATED by tools/gen_sewers.py -- do not edit.
-- Every town's sewers in brief: where the shafts and shelters are. Small, and
-- loaded everywhere: the client lights the shafts and names the street, the
-- server knows which manhole leads where. The squares are server-only (Data/).
SEW = SEW or {}
local I = { rev = "33dd38986420", towns = {}, shafts = {}, shelters = {}, journals = {}, plans = {} }
SEW.Index = I
local S, H, J, P = I.shafts, I.shelters, I.journals, I.plans
J[#J+1]={town="west_point",x=12055,y=6896,kind="squat",text="squat_2",street="Main St",dir="south"}
J[#J+1]={town="west_point",x=12132,y=6904,kind="pump",text="pump_1",street="2nd St",dir="west"}
J[#J+1]={town="west_point",x=11395,y=6787,kind="laststand",text="laststand_2",street="9th St",dir="north"}
J[#J+1]={town="west_point",x=11556,y=6815,kind="pump",text="pump_2",street="Young St",dir="north-west"}
J[#J+1]={town="west_point",x=12057,y=6959,kind="maintenance",text="maintenance_2",street="Church St",dir="south"}
J[#J+1]={town="west_point",x=11801,y=6769,kind="maintenance",text="maintenance_2",street="Oak St",dir="north"}
J[#J+1]={town="west_point",x=12055,y=6896,kind="squat",text="squat_2",street="Main St",dir="north"}
J[#J+1]={town="west_point",x=11395,y=6940,kind="laststand",text="laststand_1",street="9th St",dir="west"}
J[#J+1]={town="west_point",x=12055,y=6896,kind="squat",text="squat_2",street="Main St",dir="west"}
J[#J+1]={town="west_point",x=11696,y=6741,kind="squat",text="squat_2",street="Cabin Road",dir="west"}
J[#J+1]={town="west_point",x=11580,y=6840,kind="pump",text="pump_2",street="Mulberry St",dir="south-east"}
J[#J+1]={town="west_point",x=11162,y=6896,kind="squat",text="squat_1",street="10th St",dir="east"}
J[#J+1]={town="west_point",x=11003,y=6897,kind="pump",text="pump_1",street="Main St",dir="west"}
J[#J+1]={town="west_point",x=11580,y=6840,kind="pump",text="pump_1",street="Mulberry St",dir="north"}
J[#J+1]={town="west_point",x=11087,y=6756,kind="maintenance",text="maintenance_1",street="Oak St",dir="west"}
J[#J+1]={town="west_point",x=12245,y=6897,kind="maintenance",text="maintenance_1",street="Clarke Way",dir="south"}
J[#J+1]={town="west_point",x=11470,y=6945,kind="pump",text="pump_1",street="South St",dir="east"}
J[#J+1]={town="west_point",x=11705,y=7064,kind="laststand",text="laststand_1",street="7th St",dir="north"}
J[#J+1]={town="west_point",x=11696,y=6741,kind="squat",text="squat_1",street="Cabin Road",dir="north"}
J[#J+1]={town="west_point",x=11378,y=6853,kind="maintenance",text="maintenance_2",street="9th St",dir="south"}
J[#J+1]={town="west_point",x=11395,y=6787,kind="laststand",text="laststand_2",street="9th St",dir="south-west"}
J[#J+1]={town="west_point",x=11735,y=7179,kind="squat",text="squat_2",street="7th St",dir="south"}
J[#J+1]={town="west_point",x=11197,y=6719,kind="squat",text="squat_2",street="Miller Dr",dir="east"}
J[#J+1]={town="west_point",x=11711,y=6840,kind="squat",text="squat_1",street="Mulberry St",dir="south"}
J[#J+1]={town="west_point",x=12043,y=6833,kind="maintenance",text="maintenance_2",street="Mulberry St",dir="south-west"}
J[#J+1]={town="west_point",x=12245,y=6897,kind="maintenance",text="maintenance_2",street="Clarke Way",dir="north"}
J[#J+1]={town="muldraugh",x=10828,y=10108,kind="maintenance",text="maintenance_2",street="Lime St",dir="south"}
J[#J+1]={town="muldraugh",x=10977,y=9713,kind="squat",text="squat_2",street="Irma Dr",dir="south-east"}
J[#J+1]={town="muldraugh",x=10597,y=10326,kind="laststand",text="laststand_1",street="Wilson St",dir="north"}
J[#J+1]={town="muldraugh",x=10722,y=10620,kind="pump",text="pump_2",street="Perrine St",dir="east"}
J[#J+1]={town="muldraugh",x=10598,y=10404,kind="laststand",text="laststand_2",street="Dixie Highway (Route 31W)",dir="south"}
J[#J+1]={town="muldraugh",x=10854,y=10300,kind="maintenance",text="maintenance_1",street="S Main St",dir="south-east"}
J[#J+1]={town="muldraugh",x=10832,y=10019,kind="laststand",text="laststand_2",street="Diesel St",dir="south"}
J[#J+1]={town="muldraugh",x=10977,y=9713,kind="squat",text="squat_2",street="Irma Dr",dir="north"}
J[#J+1]={town="muldraugh",x=10722,y=10620,kind="pump",text="pump_1",street="Perrine St",dir="south"}
J[#J+1]={town="muldraugh",x=10670,y=9409,kind="squat",text="squat_1",street="N Main St",dir="east"}
J[#J+1]={town="muldraugh",x=10587,y=9399,kind="squat",text="squat_1",street="Dixie Highway (Route 31W)",dir="west"}
J[#J+1]={town="muldraugh",x=10597,y=10326,kind="laststand",text="laststand_2",street="Wilson St",dir="south"}
J[#J+1]={town="muldraugh",x=10744,y=9873,kind="maintenance",text="maintenance_2",street="Popar St",dir="south-east"}
J[#J+1]={town="muldraugh",x=10741,y=10574,kind="pump",text="pump_1",street="Perrine St",dir="north"}
J[#J+1]={town="muldraugh",x=10866,y=9905,kind="laststand",text="laststand_1",street="Matthew St",dir="east"}
J[#J+1]={town="muldraugh",x=10832,y=10019,kind="laststand",text="laststand_1",street="Diesel St",dir="north"}
J[#J+1]={town="muldraugh",x=10796,y=10274,kind="maintenance",text="maintenance_1",street="S Main St",dir="north-west"}
J[#J+1]={town="muldraugh",x=10785,y=10357,kind="pump",text="pump_2",street="S Main St",dir="north-east"}
J[#J+1]={town="muldraugh",x=10964,y=9686,kind="pump",text="pump_1",street="Irma Dr",dir="north-west"}
J[#J+1]={town="muldraugh",x=10796,y=10274,kind="maintenance",text="maintenance_2",street="S Main St",dir="north"}
J[#J+1]={town="rosewood",x=8152,y=11592,kind="pump",text="pump_2",street="Mortimer St",dir="south"}
J[#J+1]={town="rosewood",x=8460,y=12016,kind="pump",text="pump_1",street="Catkin St",dir="east"}
J[#J+1]={town="rosewood",x=8397,y=12039,kind="pump",text="pump_2",street="Catkin St",dir="east"}
J[#J+1]={town="rosewood",x=8458,y=11583,kind="squat",text="squat_2",street="Frederick Lane",dir="north"}
J[#J+1]={town="rosewood",x=8152,y=11592,kind="pump",text="pump_2",street="Mortimer St",dir="north"}
J[#J+1]={town="rosewood",x=8152,y=11592,kind="pump",text="pump_2",street="Mortimer St",dir="east"}
J[#J+1]={town="rosewood",x=8435,y=11675,kind="maintenance",text="maintenance_2",street="Schoolhouse St",dir="south"}
J[#J+1]={town="rosewood",x=8202,y=11378,kind="laststand",text="laststand_2",street="Butterfly St",dir="west"}
J[#J+1]={town="rosewood",x=8397,y=12039,kind="pump",text="pump_2",street="Catkin St",dir="west"}
J[#J+1]={town="rosewood",x=8270,y=11404,kind="maintenance",text="maintenance_1",street="Butterfly St",dir="east"}
J[#J+1]={town="rosewood",x=8000,y=11608,kind="squat",text="squat_2",street="Doctors Lane",dir="north"}
J[#J+1]={town="rosewood",x=8000,y=11608,kind="squat",text="squat_1",street="Doctors Lane",dir="south-east"}
J[#J+1]={town="rosewood",x=8151,y=11643,kind="maintenance",text="maintenance_2",street="Mortimer St",dir="south"}
J[#J+1]={town="riverside",x=6335,y=5288,kind="maintenance",text="maintenance_1",street="E Main St",dir="east"}
J[#J+1]={town="riverside",x=6382,y=5362,kind="laststand",text="laststand_1",street="Rosewood St",dir="south-east"}
J[#J+1]={town="riverside",x=6648,y=5443,kind="laststand",text="laststand_1",street="Station St",dir="east"}
J[#J+1]={town="riverside",x=6382,y=5362,kind="laststand",text="laststand_1",street="Rosewood St",dir="north"}
J[#J+1]={town="riverside",x=6730,y=5278,kind="squat",text="squat_1",street="E Main St",dir="west"}
J[#J+1]={town="riverside",x=6680,y=5542,kind="laststand",text="laststand_2",street="Kennedy St",dir="south"}
J[#J+1]={town="riverside",x=6335,y=5288,kind="maintenance",text="maintenance_1",street="E Main St",dir="north-west"}
J[#J+1]={town="riverside",x=6804,y=5288,kind="squat",text="squat_1",street="E Main St",dir="east"}
J[#J+1]={town="riverside",x=6648,y=5443,kind="laststand",text="laststand_2",street="Station St",dir="north"}
J[#J+1]={town="ekron",x=678,y=9673,kind="maintenance",text="maintenance_1",street="Reese Ave",dir="north-west"}
J[#J+1]={town="ekron",x=382,y=9776,kind="pump",text="pump_2",street="West Alley St",dir="south"}
J[#J+1]={town="ekron",x=711,y=9740,kind="pump",text="pump_2",street="Dry Alley",dir="south-east"}
J[#J+1]={town="ekron",x=678,y=9673,kind="maintenance",text="maintenance_1",street="Reese Ave",dir="west"}
J[#J+1]={town="ekron",x=472,y=9773,kind="pump",text="pump_2",street="Chism Dr",dir="west"}
J[#J+1]={town="ekron",x=382,y=9776,kind="pump",text="pump_2",street="West Alley St",dir="north-east"}
J[#J+1]={town="ekron",x=382,y=9776,kind="pump",text="pump_1",street="West Alley St",dir="west"}
J[#J+1]={town="ekron",x=472,y=9773,kind="pump",text="pump_1",street="Chism Dr",dir="east"}
J[#J+1]={town="fallas_lake",x=7330,y=8158,kind="squat",text="squat_2",street="Railview Road",dir="east"}
J[#J+1]={town="fallas_lake",x=7282,y=8327,kind="laststand",text="laststand_1",street="Main St",dir="east"}
J[#J+1]={town="fallas_lake",x=7368,y=8151,kind="maintenance",text="maintenance_2",street="Railview Road",dir="east"}
J[#J+1]={town="fallas_lake",x=7330,y=8158,kind="squat",text="squat_2",street="Railview Road",dir="west"}
J[#J+1]={town="fallas_lake",x=7215,y=8322,kind="pump",text="pump_1",street="Broadway St",dir="west"}
J[#J+1]={town="fallas_lake",x=7282,y=8327,kind="laststand",text="laststand_2",street="Main St",dir="north"}
J[#J+1]={town="louisville",x=12938,y=2493,kind="maintenance",text="maintenance_2",street="Quarantine Lane",dir="north-east"}
J[#J+1]={town="louisville",x=12895,y=2533,kind="maintenance",text="maintenance_2",street="Ulster St",dir="south-west"}
J[#J+1]={town="muldraugh_2",x=11830,y=8848,kind="shaft",text="shaft_2",street="Dixie Loop S St",dir="east"}
J[#J+1]={town="muldraugh_3",x=10357,y=9237,kind="shaft",text="shaft_2",street="",dir="north"}
J[#J+1]={town="west_point_2",x=11602,y=8230,kind="shaft",text="shaft_2",street="Riverside Road",dir="north-west"}
J[#J+1]={town="louisville_2",x=13360,y=1904,kind="shaft",text="shaft_1",street="W Market St",dir="east"}
J[#J+1]={town="brandenburg",x=3530,y=6050,kind="shaft",text="shaft_2",street="KY-60",dir="north"}
J[#J+1]={town="muldraugh_4",x=10067,y=9792,kind="shaft",text="shaft_2",street="Old Mill Road",dir="north"}
J[#J+1]={town="knox_county",x=10086,y=6682,kind="shaft",text="shaft_2",street="",dir="north"}
J[#J+1]={town="west_point_3",x=10375,y=7448,kind="shaft",text="shaft_2",street="Raccoon Road",dir="east"}
J[#J+1]={town="knox_county_2",x=15033,y=820,kind="shaft",text="shaft_1",street="",dir="south"}
P[#P+1]={town="west_point",i=3,j=0}
P[#P+1]={town="west_point",i=5,j=1}
P[#P+1]={town="west_point",i=5,j=0}
P[#P+1]={town="west_point",i=1,j=0}
P[#P+1]={town="west_point",i=3,j=0}
P[#P+1]={town="west_point",i=5,j=0}
P[#P+1]={town="west_point",i=1,j=0}
P[#P+1]={town="west_point",i=3,j=2}
P[#P+1]={town="west_point",i=1,j=0}
P[#P+1]={town="west_point",i=5,j=0}
P[#P+1]={town="west_point",i=1,j=0}
P[#P+1]={town="west_point",i=4,j=2}
P[#P+1]={town="muldraugh",i=0,j=1}
P[#P+1]={town="muldraugh",i=0,j=1}
P[#P+1]={town="muldraugh",i=0,j=0}
P[#P+1]={town="muldraugh",i=0,j=4}
P[#P+1]={town="muldraugh",i=1,j=2}
P[#P+1]={town="muldraugh",i=1,j=3}
P[#P+1]={town="muldraugh",i=1,j=1}
P[#P+1]={town="muldraugh",i=0,j=3}
P[#P+1]={town="muldraugh",i=1,j=2}
P[#P+1]={town="muldraugh",i=1,j=2}
P[#P+1]={town="rosewood",i=1,j=2}
P[#P+1]={town="rosewood",i=0,j=1}
P[#P+1]={town="rosewood",i=1,j=0}
P[#P+1]={town="rosewood",i=0,j=0}
P[#P+1]={town="rosewood",i=1,j=1}
P[#P+1]={town="rosewood",i=1,j=2}
P[#P+1]={town="rosewood",i=0,j=0}
P[#P+1]={town="riverside",i=2,j=1}
P[#P+1]={town="riverside",i=2,j=1}
P[#P+1]={town="ekron",i=0,j=1}
P[#P+1]={town="ekron",i=2,j=0}
P[#P+1]={town="ekron",i=2,j=1}
P[#P+1]={town="ekron",i=1,j=0}
P[#P+1]={town="ekron",i=1,j=1}
P[#P+1]={town="ekron",i=2,j=0}
P[#P+1]={town="fallas_lake",i=0,j=1}
P[#P+1]={town="fallas_lake",i=0,j=1}
P[#P+1]={town="louisville",i=0,j=2}
P[#P+1]={town="louisville",i=0,j=1}
P[#P+1]={town="muldraugh_2",i=1,j=0}
P[#P+1]={town="west_point_2",i=0,j=0}
P[#P+1]={town="louisville_2",i=0,j=0}
P[#P+1]={town="brandenburg",i=0,j=0}
P[#P+1]={town="muldraugh_4",i=0,j=0}
P[#P+1]={town="west_point_3",i=0,j=0}
I.towns["west_point"] = { name = "West Point", x0 = 10876, y0 = 6648, x1 = 12338, y1 = 7217, tw = 6, th = 3, chunks = 1898 }
S["10916,6902"]={town="west_point",x=10916,y=6902,lx=10916,ly=6902,edge="W",street="Main St"}
S["10951,6898"]={town="west_point",x=10951,y=6898,lx=10951,ly=6898,edge="N",street="Main St"}
S["10963,6693"]={town="west_point",x=10963,y=6693,lx=10963,ly=6693,edge="N",street="Oak St"}
S["11016,6753"]={town="west_point",x=11016,y=6753,lx=11016,ly=6753,edge="W",street="Oak St"}
S["11107,6753"]={town="west_point",x=11107,y=6753,lx=11107,ly=6753,edge="W",street="Oak St"}
S["11187,6712"]={town="west_point",x=11187,y=6712,lx=11187,ly=6712,edge="N",street="Miller Dr"}
S["11191,6748"]={town="west_point",x=11191,y=6748,lx=11191,ly=6748,edge="N",street="Oak St"}
S["11259,6731"]={town="west_point",x=11259,y=6731,lx=11259,ly=6731,edge="N",street="10th St"}
S["11264,6878"]={town="west_point",x=11264,y=6878,lx=11264,ly=6878,edge="N",street="10th St"}
S["11280,6936"]={town="west_point",x=11280,y=6936,lx=11280,ly=6936,edge="W",street=""}
S["11284,6688"]={town="west_point",x=11284,y=6688,lx=11284,ly=6688,edge="N",street="Ohio Dr"}
S["11312,6693"]={town="west_point",x=11312,y=6693,lx=11312,ly=6693,edge="W",street="Ohio Dr"}
S["11325,6752"]={town="west_point",x=11325,y=6752,lx=11325,ly=6753,edge="N",street="Oak St"}
S["11331,6898"]={town="west_point",x=11331,y=6898,lx=11331,ly=6898,edge="N",street="Main St"}
S["11345,6747"]={town="west_point",x=11345,y=6747,lx=11345,ly=6747,edge="N",street="Oak St"}
S["11359,6693"]={town="west_point",x=11359,y=6693,lx=11359,ly=6693,edge="W",street="Ohio Dr"}
S["11362,6739"]={town="west_point",x=11362,y=6739,lx=11362,ly=6739,edge="N",street="River St"}
S["11366,6809"]={town="west_point",x=11366,y=6809,lx=11366,ly=6809,edge="N",street=""}
S["11388,6693"]={town="west_point",x=11388,y=6693,lx=11388,ly=6693,edge="W",street="Ohio Dr"}
S["11392,6771"]={town="west_point",x=11392,y=6771,lx=11392,ly=6771,edge="W",street="9th St"}
S["11398,6832"]={town="west_point",x=11398,y=6832,lx=11398,ly=6833,edge="N",street="9th St"}
S["11402,6955"]={town="west_point",x=11402,y=6955,lx=11402,ly=6955,edge="N",street="9th St"}
S["11409,6826"]={town="west_point",x=11409,y=6826,lx=11409,ly=6826,edge="W",street="Young St"}
S["11414,6902"]={town="west_point",x=11414,y=6902,lx=11414,ly=6902,edge="W",street="Main St"}
S["11422,7047"]={town="west_point",x=11422,y=7047,lx=11422,ly=7047,edge="W",street="Duffield St"}
S["11458,6826"]={town="west_point",x=11458,y=6826,lx=11458,ly=6826,edge="W",street="Young St"}
S["11469,6951"]={town="west_point",x=11469,y=6951,lx=11469,ly=6951,edge="W",street="South St"}
S["11471,6724"]={town="west_point",x=11471,y=6724,lx=11471,ly=6724,edge="N",street="Short St"}
S["11482,6897"]={town="west_point",x=11482,y=6897,lx=11482,ly=6897,edge="N",street="Main St"}
S["11532,7044"]={town="west_point",x=11532,y=7044,lx=11532,ly=7044,edge="W",street="Rosenwald St"}
S["11535,6819"]={town="west_point",x=11535,y=6819,lx=11535,ly=6819,edge="N",street="Young St"}
S["11538,6996"]={town="west_point",x=11538,y=6996,lx=11538,ly=6996,edge="N",street="Bulletin St"}
S["11548,6888"]={town="west_point",x=11548,y=6888,lx=11548,ly=6888,edge="N",street="8th St"}
S["11549,6774"]={town="west_point",x=11549,y=6774,lx=11549,ly=6774,edge="N",street="8th St"}
S["11553,6971"]={town="west_point",x=11553,y=6971,lx=11554,ly=6971,edge="W",street="8th St"}
S["11561,6946"]={town="west_point",x=11561,y=6946,lx=11561,ly=6946,edge="N",street="South St"}
S["11600,6832"]={town="west_point",x=11600,y=6832,lx=11600,ly=6832,edge="N",street="Mulberry St"}
S["11603,6976"]={town="west_point",x=11603,y=6976,lx=11603,ly=6976,edge="N",street="Rosenwald St"}
S["11623,6914"]={town="west_point",x=11623,y=6914,lx=11623,ly=6914,edge="N",street="Lacey Lane"}
S["11626,6759"]={town="west_point",x=11626,y=6759,lx=11626,ly=6759,edge="N",street="Oak St"}
S["11627,6690"]={town="west_point",x=11627,y=6690,lx=11627,ly=6690,edge="N",street="Fishers Lane"}
S["11634,6951"]={town="west_point",x=11634,y=6951,lx=11634,ly=6951,edge="W",street="South St"}
S["11654,7057"]={town="west_point",x=11654,y=7057,lx=11654,ly=7057,edge="W",street=""}
S["11679,6776"]={town="west_point",x=11679,y=6776,lx=11679,ly=6776,edge="W",street="Oak St"}
S["11682,6832"]={town="west_point",x=11682,y=6832,lx=11682,ly=6832,edge="N",street="Mulberry St"}
S["11685,6902"]={town="west_point",x=11685,y=6902,lx=11685,ly=6902,edge="W",street="Main St"}
S["11687,7100"]={town="west_point",x=11687,y=7100,lx=11687,ly=7100,edge="N",street="7th St"}
S["11697,6726"]={town="west_point",x=11697,y=6726,lx=11697,ly=6726,edge="N",street="Cabin Road"}
S["11697,6791"]={town="west_point",x=11697,y=6791,lx=11697,ly=6791,edge="N",street="7th St"}
S["11698,7029"]={town="west_point",x=11698,y=7029,lx=11698,ly=7030,edge="N",street="7th St"}
S["11701,6715"]={town="west_point",x=11701,y=6715,lx=11701,ly=6715,edge="N",street="Cabin Road"}
S["11710,6897"]={town="west_point",x=11710,y=6897,lx=11710,ly=6897,edge="N",street="Main St"}
S["11729,6770"]={town="west_point",x=11729,y=6770,lx=11729,ly=6770,edge="N",street="Oak St"}
S["11744,6941"]={town="west_point",x=11744,y=6941,lx=11744,ly=6941,edge="W",street=""}
S["11750,6710"]={town="west_point",x=11750,y=6710,lx=11750,ly=6710,edge="W",street="Cabin Road"}
S["11750,6868"]={town="west_point",x=11750,y=6868,lx=11750,ly=6868,edge="N",street=""}
S["11754,6833"]={town="west_point",x=11754,y=6833,lx=11754,ly=6833,edge="N",street="Mulberry St"}
S["11759,6902"]={town="west_point",x=11759,y=6902,lx=11759,ly=6902,edge="W",street="Main St"}
S["11769,6911"]={town="west_point",x=11769,y=6911,lx=11769,ly=6911,edge="N",street="6th St"}
S["11771,6811"]={town="west_point",x=11771,y=6811,lx=11771,ly=6812,edge="N",street="6th St"}
S["11775,6887"]={town="west_point",x=11775,y=6887,lx=11775,ly=6887,edge="N",street="6th St"}
S["11788,6865"]={town="west_point",x=11788,y=6865,lx=11788,ly=6865,edge="N",street="6th St"}
S["11797,6791"]={town="west_point",x=11797,y=6791,lx=11797,ly=6791,edge="N",street="Oak St"}
S["11806,6705"]={town="west_point",x=11806,y=6705,lx=11806,ly=6705,edge="N",street="Cabin Road"}
S["11808,6889"]={town="west_point",x=11808,y=6889,lx=11808,ly=6889,edge="N",street="Main St"}
S["11808,6959"]={town="west_point",x=11808,y=6959,lx=11808,ly=6959,edge="N",street="Church St"}
S["11809,6827"]={town="west_point",x=11809,y=6827,lx=11809,ly=6827,edge="N",street="Mulberry St"}
S["11810,6926"]={town="west_point",x=11810,y=6926,lx=11810,ly=6926,edge="N",street=""}
S["11827,6775"]={town="west_point",x=11827,y=6775,lx=11827,ly=6775,edge="W",street="Oak St"}
S["11832,6870"]={town="west_point",x=11832,y=6870,lx=11832,ly=6870,edge="N",street="5th St"}
S["11837,6832"]={town="west_point",x=11837,y=6832,lx=11837,ly=6832,edge="N",street="Mulberry St"}
S["11845,6952"]={town="west_point",x=11845,y=6952,lx=11845,ly=6952,edge="N",street="5th St"}
S["11850,6717"]={town="west_point",x=11850,y=6717,lx=11850,ly=6717,edge="N",street="5th St"}
S["11854,6800"]={town="west_point",x=11854,y=6800,lx=11854,ly=6800,edge="N",street="5th St"}
S["11855,6938"]={town="west_point",x=11855,y=6938,lx=11855,ly=6938,edge="N",street="5th St"}
S["11858,6838"]={town="west_point",x=11858,y=6838,lx=11858,ly=6838,edge="W",street="Mulberry St"}
S["11871,7041"]={town="west_point",x=11871,y=7041,lx=11871,ly=7041,edge="N",street="Derry Close"}
S["11874,6710"]={town="west_point",x=11874,y=6710,lx=11874,ly=6710,edge="W",street="Cabin Road"}
S["11874,6849"]={town="west_point",x=11874,y=6849,lx=11874,ly=6849,edge="W",street="Mulberry St"}
S["11885,6893"]={town="west_point",x=11885,y=6893,lx=11885,ly=6893,edge="N",street="Main St"}
S["11907,6783"]={town="west_point",x=11907,y=6783,lx=11907,ly=6783,edge="W",street="Oak St"}
S["11913,6717"]={town="west_point",x=11913,y=6717,lx=11913,ly=6717,edge="N",street="Cabin Road"}
S["11917,6832"]={town="west_point",x=11917,y=6832,lx=11917,ly=6832,edge="W",street="4th St"}
S["11918,6878"]={town="west_point",x=11918,y=6878,lx=11918,ly=6878,edge="N",street="4th St"}
S["11918,6953"]={town="west_point",x=11918,y=6953,lx=11918,ly=6953,edge="N",street="4th St"}
S["11922,6790"]={town="west_point",x=11922,y=6790,lx=11923,ly=6790,edge="W",street="4th St"}
S["11923,7037"]={town="west_point",x=11923,y=7037,lx=11923,ly=7037,edge="N",street="4th St"}
S["11933,6902"]={town="west_point",x=11933,y=6902,lx=11933,ly=6902,edge="W",street="Main St"}
S["11935,7020"]={town="west_point",x=11935,y=7020,lx=11935,ly=7020,edge="N",street="4th St"}
S["11937,6834"]={town="west_point",x=11937,y=6834,lx=11937,ly=6834,edge="N",street="Mulberry St"}
S["11940,6935"]={town="west_point",x=11940,y=6935,lx=11940,ly=6935,edge="N",street="4th St"}
S["11941,6775"]={town="west_point",x=11941,y=6775,lx=11941,ly=6775,edge="W",street="Oak St"}
S["11946,6797"]={town="west_point",x=11946,y=6797,lx=11946,ly=6797,edge="W",street=""}
S["11965,6897"]={town="west_point",x=11965,y=6897,lx=11965,ly=6897,edge="N",street="Main St"}
S["11973,6959"]={town="west_point",x=11973,y=6959,lx=11973,ly=6959,edge="N",street="Church St"}
S["11976,6922"]={town="west_point",x=11976,y=6922,lx=11976,ly=6922,edge="N",street=""}
S["11993,6790"]={town="west_point",x=11993,y=6790,lx=11993,ly=6790,edge="N",street="3rd St"}
S["11997,6878"]={town="west_point",x=11997,y=6878,lx=11997,ly=6878,edge="N",street="3rd St"}
S["11997,6922"]={town="west_point",x=11997,y=6922,lx=11997,ly=6922,edge="N",street="3rd St"}
S["12002,6987"]={town="west_point",x=12002,y=6987,lx=12002,ly=6987,edge="N",street="3rd St"}
S["12002,7062"]={town="west_point",x=12002,y=7062,lx=12002,ly=7062,edge="N",street="3rd St"}
S["12002,7117"]={town="west_point",x=12002,y=7117,lx=12002,ly=7117,edge="N",street=""}
S["12010,6897"]={town="west_point",x=12010,y=6897,lx=12010,ly=6897,edge="N",street="Main St"}
S["12013,6770"]={town="west_point",x=12013,y=6770,lx=12013,ly=6770,edge="N",street="Oak St"}
S["12020,6833"]={town="west_point",x=12020,y=6833,lx=12020,ly=6833,edge="N",street="Mulberry St"}
S["12022,7177"]={town="west_point",x=12022,y=7177,lx=12022,ly=7177,edge="N",street="Dixie Highway (Route 31W)"}
S["12025,6775"]={town="west_point",x=12025,y=6775,lx=12025,ly=6775,edge="W",street="Oak St"}
S["12027,6950"]={town="west_point",x=12027,y=6950,lx=12027,ly=6950,edge="N",street="Church St"}
S["12052,6879"]={town="west_point",x=12052,y=6879,lx=12052,ly=6879,edge="N",street=""}
S["12066,6850"]={town="west_point",x=12066,y=6850,lx=12066,ly=6850,edge="N",street="Mulberry St"}
S["12080,7172"]={town="west_point",x=12080,y=7172,lx=12080,ly=7172,edge="N",street="Dixie Highway (Route 31W)"}
S["12084,6838"]={town="west_point",x=12084,y=6838,lx=12084,ly=6838,edge="W",street="Mulberry St"}
S["12085,7172"]={town="west_point",x=12085,y=7172,lx=12085,ly=7172,edge="N",street="Dixie Highway (Route 31W)"}
S["12087,6822"]={town="west_point",x=12087,y=6822,lx=12087,ly=6822,edge="N",street="Mulberry St"}
S["12089,7133"]={town="west_point",x=12089,y=7133,lx=12089,ly=7133,edge="N",street="2nd St"}
S["12091,7172"]={town="west_point",x=12091,y=7172,lx=12091,ly=7172,edge="N",street="Dixie Highway (Route 31W)"}
S["12098,6770"]={town="west_point",x=12098,y=6770,lx=12098,ly=6770,edge="N",street="Oak St"}
S["12101,6958"]={town="west_point",x=12101,y=6958,lx=12101,ly=6958,edge="W",street="2nd St"}
S["12103,7022"]={town="west_point",x=12103,y=7022,lx=12103,ly=7022,edge="N",street="2nd St"}
S["12108,6910"]={town="west_point",x=12108,y=6910,lx=12108,ly=6910,edge="N",street="2nd St"}
S["12108,7121"]={town="west_point",x=12108,y=7121,lx=12108,ly=7121,edge="N",street="2nd St"}
S["12112,6849"]={town="west_point",x=12112,y=6849,lx=12112,ly=6849,edge="N",street="Oak St"}
S["12112,6892"]={town="west_point",x=12112,y=6892,lx=12112,ly=6892,edge="N",street="Oak St"}
S["12151,6930"]={town="west_point",x=12151,y=6930,lx=12151,ly=6930,edge="W",street=""}
S["12163,7060"]={town="west_point",x=12163,y=7060,lx=12163,ly=7060,edge="N",street="Northern Railroad (Muldraugh - Doe Valley)"}
S["12209,6897"]={town="west_point",x=12209,y=6897,lx=12209,ly=6897,edge="N",street="Clarke Way"}
S["12226,6930"]={town="west_point",x=12226,y=6930,lx=12226,ly=6930,edge="N",street="Dixie Highway (Route 31W)"}
S["12227,7151"]={town="west_point",x=12227,y=7151,lx=12227,ly=7151,edge="N",street="Dixie Highway (Route 31W)"}
S["12234,7043"]={town="west_point",x=12234,y=7043,lx=12235,ly=7043,edge="W",street="Dixie Highway (Route 31W)"}
S["12277,6968"]={town="west_point",x=12277,y=6968,lx=12277,ly=6968,edge="N",street="Clarke Way"}
S["12298,6927"]={town="west_point",x=12298,y=6927,lx=12298,ly=6927,edge="N",street="Clarke Way"}
H[#H+1]={town="west_point",kind="maintenance",x=12041,y=6831,w=5,h=4}
H[#H+1]={town="west_point",kind="maintenance",x=12242,y=6895,w=6,h=4}
H[#H+1]={town="west_point",kind="maintenance",x=11374,y=6850,w=8,h=6}
H[#H+1]={town="west_point",kind="pump",x=11578,y=6838,w=5,h=4}
H[#H+1]={town="west_point",kind="squat",x=12053,y=6894,w=5,h=5}
H[#H+1]={town="west_point",kind="squat",x=11804,y=6902,w=5,h=5}
H[#H+1]={town="west_point",kind="maintenance",x=12054,y=6957,w=7,h=5}
H[#H+1]={town="west_point",kind="pump",x=11467,y=6942,w=7,h=6}
H[#H+1]={town="west_point",kind="pump",x=12128,y=6902,w=8,h=4}
H[#H+1]={town="west_point",kind="maintenance",x=11799,y=6766,w=5,h=6}
H[#H+1]={town="west_point",kind="pump",x=11554,y=6812,w=5,h=6}
H[#H+1]={town="west_point",kind="pump",x=10999,y=6895,w=8,h=4}
H[#H+1]={town="west_point",kind="squat",x=11159,y=6893,w=6,h=6}
H[#H+1]={town="west_point",kind="squat",x=11589,y=6895,w=5,h=4}
H[#H+1]={town="west_point",kind="squat",x=11195,y=6716,w=5,h=6}
H[#H+1]={town="west_point",kind="maintenance",x=12295,y=6742,w=7,h=6}
H[#H+1]={town="west_point",kind="laststand",x=11391,y=6938,w=8,h=5}
H[#H+1]={town="west_point",kind="squat",x=11731,y=7177,w=8,h=4}
H[#H+1]={town="west_point",kind="squat",x=11708,y=6838,w=6,h=4}
H[#H+1]={town="west_point",kind="laststand",x=11391,y=6785,w=8,h=4}
H[#H+1]={town="west_point",kind="laststand",x=11445,y=6686,w=7,h=4}
H[#H+1]={town="west_point",kind="laststand",x=11702,y=7061,w=6,h=6}
H[#H+1]={town="west_point",kind="maintenance",x=11084,y=6753,w=7,h=6}
H[#H+1]={town="west_point",kind="squat",x=11693,y=6738,w=6,h=6}
H[#H+1]={town="west_point",kind="squat",x=12099,y=6767,w=8,h=5}
H[#H+1]={town="west_point",kind="laststand",x=12235,y=7068,w=7,h=5}
I.towns["muldraugh"] = { name = "Muldraugh", x0 = 10557, y0 = 9198, x1 = 11126, y1 = 10697, tw = 3, th = 6, chunks = 2141 }
S["10597,10163"]={town="muldraugh",x=10597,y=10163,lx=10597,ly=10163,edge="N",street="Dixie Highway (Route 31W)"}
S["10603,9526"]={town="muldraugh",x=10603,y=9526,lx=10603,ly=9526,edge="N",street="Dixie Highway (Route 31W)"}
S["10604,10235"]={town="muldraugh",x=10604,y=10235,lx=10604,ly=10235,edge="N",street="Dixie Highway (Route 31W)"}
S["10604,10427"]={town="muldraugh",x=10604,y=10427,lx=10604,ly=10427,edge="N",street="Dixie Highway (Route 31W)"}
S["10606,9455"]={town="muldraugh",x=10606,y=9455,lx=10606,ly=9455,edge="N",street="Dixie Highway (Route 31W)"}
S["10608,9916"]={town="muldraugh",x=10608,y=9916,lx=10608,ly=9916,edge="N",street="Dixie Highway (Route 31W)"}
S["10608,10026"]={town="muldraugh",x=10608,y=10026,lx=10608,ly=10026,edge="N",street="Dixie Highway (Route 31W)"}
S["10610,9392"]={town="muldraugh",x=10610,y=9392,lx=10610,ly=9392,edge="N",street="Dixie Highway (Route 31W)"}
S["10612,9579"]={town="muldraugh",x=10612,y=9579,lx=10612,ly=9579,edge="N",street="Dixie Highway (Route 31W)"}
S["10613,9247"]={town="muldraugh",x=10613,y=9247,lx=10613,ly=9247,edge="N",street=""}
S["10615,10106"]={town="muldraugh",x=10615,y=10106,lx=10615,ly=10106,edge="W",street="W Maple St"}
S["10617,9781"]={town="muldraugh",x=10617,y=9781,lx=10617,ly=9781,edge="N",street=""}
S["10622,10391"]={town="muldraugh",x=10622,y=10391,lx=10622,ly=10392,edge="N",street="Wilson St"}
S["10623,10444"]={town="muldraugh",x=10623,y=10444,lx=10623,ly=10444,edge="W",street="Wilson St"}
S["10624,9668"]={town="muldraugh",x=10624,y=9668,lx=10624,ly=9668,edge="N",street=""}
S["10624,10349"]={town="muldraugh",x=10624,y=10349,lx=10624,ly=10349,edge="N",street="Wilson St"}
S["10624,10600"]={town="muldraugh",x=10624,y=10600,lx=10624,ly=10600,edge="N",street=""}
S["10625,10283"]={town="muldraugh",x=10625,y=10283,lx=10626,ly=10283,edge="W",street="Wilson St"}
S["10630,10458"]={town="muldraugh",x=10630,y=10458,lx=10630,ly=10458,edge="N",street="Wilson St"}
S["10631,9734"]={town="muldraugh",x=10631,y=9734,lx=10631,ly=9734,edge="N",street="W Garnettsville Road"}
S["10634,9613"]={town="muldraugh",x=10634,y=9613,lx=10634,ly=9613,edge="N",street="N Main St"}
S["10639,9962"]={town="muldraugh",x=10639,y=9962,lx=10639,ly=9963,edge="N",street="Wilson St"}
S["10639,10091"]={town="muldraugh",x=10639,y=10091,lx=10639,ly=10092,edge="N",street="Wilson St"}
S["10641,10438"]={town="muldraugh",x=10641,y=10438,lx=10642,ly=10438,edge="W",street="Wilson St"}
S["10642,9767"]={town="muldraugh",x=10642,y=9767,lx=10642,ly=9767,edge="N",street=""}
S["10643,10325"]={town="muldraugh",x=10643,y=10325,lx=10643,ly=10325,edge="N",street="Wilson St"}
S["10644,9238"]={town="muldraugh",x=10644,y=9238,lx=10645,ly=9238,edge="W",street="Old Bank Road"}
S["10645,10495"]={town="muldraugh",x=10645,y=10495,lx=10646,ly=10495,edge="W",street="Wilson St"}
S["10647,10157"]={town="muldraugh",x=10647,y=10157,lx=10647,ly=10158,edge="N",street="Branch Dr"}
S["10658,10419"]={town="muldraugh",x=10658,y=10419,lx=10658,ly=10419,edge="N",street=""}
S["10661,9510"]={town="muldraugh",x=10661,y=9510,lx=10661,ly=9510,edge="W",street="Harris St"}
S["10662,10657"]={town="muldraugh",x=10662,y=10657,lx=10662,ly=10657,edge="N",street="Chenault St"}
S["10664,9873"]={town="muldraugh",x=10664,y=9873,lx=10664,ly=9874,edge="N",street="Hill St"}
S["10669,9708"]={town="muldraugh",x=10669,y=9708,lx=10669,ly=9708,edge="N",street="Bank Road"}
S["10672,9946"]={town="muldraugh",x=10672,y=9946,lx=10672,ly=9946,edge="W",street="Wendell St"}
S["10673,9360"]={town="muldraugh",x=10673,y=9360,lx=10673,ly=9360,edge="W",street="N Main St"}
S["10677,9629"]={town="muldraugh",x=10677,y=9629,lx=10677,ly=9629,edge="W",street="S Main St"}
S["10677,10045"]={town="muldraugh",x=10677,y=10045,lx=10677,ly=10045,edge="N",street=""}
S["10678,9564"]={town="muldraugh",x=10678,y=9564,lx=10678,ly=9564,edge="W",street="Harris Court"}
S["10680,9791"]={town="muldraugh",x=10680,y=9791,lx=10680,ly=9791,edge="W",street="Sunstar Way"}
S["10695,10468"]={town="muldraugh",x=10695,y=10468,lx=10695,ly=10468,edge="N",street=""}
S["10697,9439"]={town="muldraugh",x=10697,y=9439,lx=10697,ly=9439,edge="W",street="Walker Road"}
S["10706,10154"]={town="muldraugh",x=10706,y=10154,lx=10706,ly=10154,edge="N",street="Branch Dr"}
S["10711,10097"]={town="muldraugh",x=10711,y=10097,lx=10711,ly=10097,edge="N",street=""}
S["10713,10352"]={town="muldraugh",x=10713,y=10352,lx=10713,ly=10352,edge="N",street=""}
S["10718,10012"]={town="muldraugh",x=10718,y=10012,lx=10718,ly=10012,edge="N",street=""}
S["10734,10167"]={town="muldraugh",x=10734,y=10167,lx=10734,ly=10167,edge="N",street="Perrine St"}
S["10734,10606"]={town="muldraugh",x=10734,y=10606,lx=10734,ly=10606,edge="N",street="Perrine St"}
S["10735,9530"]={town="muldraugh",x=10735,y=9530,lx=10735,ly=9530,edge="N",street="Harris Court"}
S["10735,10313"]={town="muldraugh",x=10735,y=10313,lx=10735,ly=10314,edge="N",street="Perrine St"}
S["10735,10390"]={town="muldraugh",x=10735,y=10390,lx=10735,ly=10391,edge="N",street="Perrine St"}
S["10736,10457"]={town="muldraugh",x=10736,y=10457,lx=10736,ly=10457,edge="N",street="Perrine St"}
S["10738,9592"]={town="muldraugh",x=10738,y=9592,lx=10738,ly=9592,edge="N",street=""}
S["10739,10122"]={town="muldraugh",x=10739,y=10122,lx=10739,ly=10122,edge="N",street="Perrine St"}
S["10739,10225"]={town="muldraugh",x=10739,y=10225,lx=10739,ly=10225,edge="N",street="Wood St"}
S["10739,10283"]={town="muldraugh",x=10739,y=10283,lx=10739,ly=10283,edge="N",street="Perrine St"}
S["10740,9739"]={town="muldraugh",x=10740,y=9739,lx=10740,ly=9739,edge="W",street="W Garnettsville Road"}
S["10740,9869"]={town="muldraugh",x=10740,y=9869,lx=10741,ly=9869,edge="W",street="Popar St"}
S["10741,9677"]={town="muldraugh",x=10741,y=9677,lx=10741,ly=9677,edge="W",street="Farmer's Lane"}
S["10746,10197"]={town="muldraugh",x=10746,y=10197,lx=10746,ly=10197,edge="N",street="Perrine St"}
S["10753,9994"]={town="muldraugh",x=10753,y=9994,lx=10753,ly=9994,edge="N",street="Perrine St"}
S["10758,10046"]={town="muldraugh",x=10758,y=10046,lx=10758,ly=10046,edge="N",street="Perrine St"}
S["10762,9772"]={town="muldraugh",x=10762,y=9772,lx=10762,ly=9772,edge="N",street="S Main St"}
S["10763,10565"]={town="muldraugh",x=10763,y=10565,lx=10763,ly=10565,edge="N",street=""}
S["10775,10004"]={town="muldraugh",x=10775,y=10004,lx=10775,ly=10004,edge="N",street="Elm Court"}
S["10777,9508"]={town="muldraugh",x=10777,y=9508,lx=10777,ly=9508,edge="N",street="Harris St"}
S["10787,10657"]={town="muldraugh",x=10787,y=10657,lx=10787,ly=10657,edge="N",street="Lizard Road"}
S["10788,10284"]={town="muldraugh",x=10788,y=10284,lx=10788,ly=10285,edge="N",street="S Main St"}
S["10791,10411"]={town="muldraugh",x=10791,y=10411,lx=10792,ly=10411,edge="W",street="S Main St"}
S["10797,10226"]={town="muldraugh",x=10797,y=10226,lx=10797,ly=10226,edge="N",street="Wood St"}
S["10810,9791"]={town="muldraugh",x=10810,y=9791,lx=10810,ly=9791,edge="W",street="S Main St"}
S["10816,9938"]={town="muldraugh",x=10816,y=9938,lx=10816,ly=9938,edge="N",street="S Main St"}
S["10822,9462"]={town="muldraugh",x=10822,y=9462,lx=10822,ly=9462,edge="N",street="Walker Road"}
S["10824,9867"]={town="muldraugh",x=10824,y=9867,lx=10824,ly=9867,edge="W",street="Irma Dr"}
S["10824,10051"]={town="muldraugh",x=10824,y=10051,lx=10824,ly=10051,edge="N",street="Lime St"}
S["10855,10022"]={town="muldraugh",x=10855,y=10022,lx=10855,ly=10022,edge="N",street="Diesel St"}
S["10855,10067"]={town="muldraugh",x=10855,y=10067,lx=10855,ly=10068,edge="N",street="Dewey St"}
S["10855,10196"]={town="muldraugh",x=10855,y=10196,lx=10855,ly=10197,edge="N",street="E Maple St"}
S["10856,9983"]={town="muldraugh",x=10856,y=9983,lx=10856,ly=9984,edge="N",street="Diesel St"}
S["10857,9772"]={town="muldraugh",x=10857,y=9772,lx=10857,ly=9772,edge="W",street="Hop Lane"}
S["10861,9870"]={town="muldraugh",x=10861,y=9870,lx=10861,ly=9870,edge="W",street="Irma Dr"}
S["10870,9935"]={town="muldraugh",x=10870,y=9935,lx=10870,ly=9935,edge="W",street="Matthew St"}
S["10871,9510"]={town="muldraugh",x=10871,y=9510,lx=10871,ly=9510,edge="W",street="Harris St"}
S["10879,10053"]={town="muldraugh",x=10879,y=10053,lx=10879,ly=10053,edge="N",street="S Main St"}
S["10892,9974"]={town="muldraugh",x=10892,y=9974,lx=10892,ly=9974,edge="N",street="S Main St"}
S["10893,10134"]={town="muldraugh",x=10893,y=10134,lx=10893,ly=10134,edge="N",street="E Maple St"}
S["10895,10062"]={town="muldraugh",x=10895,y=10062,lx=10895,ly=10062,edge="N",street="E Maple St"}
S["10908,9438"]={town="muldraugh",x=10908,y=9438,lx=10908,ly=9438,edge="N",street=""}
S["10914,9770"]={town="muldraugh",x=10914,y=9770,lx=10914,ly=9770,edge="N",street="Hop Lane"}
S["10921,9804"]={town="muldraugh",x=10921,y=9804,lx=10921,ly=9804,edge="N",street="Irma Dr"}
S["10924,9464"]={town="muldraugh",x=10924,y=9464,lx=10924,ly=9464,edge="W",street="Walker Road"}
S["10924,9646"]={town="muldraugh",x=10924,y=9646,lx=10924,ly=9647,edge="N",street="Irma Dr"}
S["10926,9590"]={town="muldraugh",x=10926,y=9590,lx=10926,ly=9590,edge="N",street="Irma Dr"}
S["10926,9715"]={town="muldraugh",x=10926,y=9715,lx=10926,ly=9715,edge="N",street="Irma Dr"}
S["10926,9856"]={town="muldraugh",x=10926,y=9856,lx=10926,ly=9856,edge="N",street="Irma Dr"}
S["10934,9507"]={town="muldraugh",x=10934,y=9507,lx=10934,ly=9507,edge="N",street="Irma Dr"}
S["10937,10015"]={town="muldraugh",x=10937,y=10015,lx=10937,ly=10015,edge="N",street="S Main St"}
S["11004,9400"]={town="muldraugh",x=11004,y=9400,lx=11004,ly=9400,edge="W",street="Irma Dr"}
S["11086,9317"]={town="muldraugh",x=11086,y=9317,lx=11086,ly=9317,edge="N",street="Irma Dr"}
H[#H+1]={town="muldraugh",kind="laststand",x=10829,y=10017,w=7,h=5}
H[#H+1]={town="muldraugh",kind="pump",x=10960,y=9684,w=8,h=4}
H[#H+1]={town="muldraugh",kind="laststand",x=10595,y=10402,w=6,h=5}
H[#H+1]={town="muldraugh",kind="laststand",x=10611,y=10596,w=6,h=4}
H[#H+1]={town="muldraugh",kind="laststand",x=10595,y=10324,w=5,h=4}
H[#H+1]={town="muldraugh",kind="maintenance",x=10792,y=10271,w=8,h=6}
H[#H+1]={town="muldraugh",kind="laststand",x=10862,y=9903,w=8,h=4}
H[#H+1]={town="muldraugh",kind="maintenance",x=11023,y=9842,w=5,h=4}
H[#H+1]={town="muldraugh",kind="pump",x=10739,y=10572,w=5,h=5}
H[#H+1]={town="muldraugh",kind="squat",x=10585,y=9396,w=5,h=6}
H[#H+1]={town="muldraugh",kind="squat",x=10667,y=9406,w=7,h=6}
H[#H+1]={town="muldraugh",kind="squat",x=10600,y=10092,w=5,h=4}
H[#H+1]={town="muldraugh",kind="maintenance",x=10632,y=9732,w=7,h=4}
H[#H+1]={town="muldraugh",kind="pump",x=10719,y=10617,w=6,h=6}
H[#H+1]={town="muldraugh",kind="maintenance",x=10741,y=9870,w=6,h=6}
H[#H+1]={town="muldraugh",kind="maintenance",x=10825,y=10106,w=7,h=5}
H[#H+1]={town="muldraugh",kind="maintenance",x=10850,y=10298,w=8,h=5}
H[#H+1]={town="muldraugh",kind="laststand",x=10739,y=10442,w=7,h=5}
H[#H+1]={town="muldraugh",kind="squat",x=10974,y=9711,w=6,h=5}
H[#H+1]={town="muldraugh",kind="pump",x=10782,y=10355,w=7,h=5}
I.towns["rosewood"] = { name = "Rosewood", x0 = 7870, y0 = 11341, x1 = 8502, y1 = 12053, tw = 3, th = 3, chunks = 1061 }
S["7910,11515"]={town="rosewood",x=7910,y=11515,lx=7910,ly=11515,edge="W",street=""}
S["7914,11476"]={town="rosewood",x=7914,y=11476,lx=7914,ly=11477,edge="N",street="Quiet St"}
S["7916,11382"]={town="rosewood",x=7916,y=11382,lx=7916,ly=11382,edge="N",street="Snake St"}
S["7931,11511"]={town="rosewood",x=7931,y=11511,lx=7931,ly=11511,edge="N",street=""}
S["7963,11381"]={town="rosewood",x=7963,y=11381,lx=7963,ly=11381,edge="N",street="Snake St"}
S["7970,11476"]={town="rosewood",x=7970,y=11476,lx=7970,ly=11477,edge="N",street="Quiet St"}
S["8010,11664"]={town="rosewood",x=8010,y=11664,lx=8010,ly=11664,edge="N",street=""}
S["8018,11474"]={town="rosewood",x=8018,y=11474,lx=8018,ly=11474,edge="N",street="Quiet St"}
S["8025,11536"]={town="rosewood",x=8025,y=11536,lx=8025,ly=11536,edge="W",street="Doctors Lane"}
S["8026,11417"]={town="rosewood",x=8026,y=11417,lx=8026,ly=11417,edge="N",street="Shelf St"}
S["8026,11570"]={town="rosewood",x=8026,y=11570,lx=8026,ly=11570,edge="N",street="Doctors Lane"}
S["8027,11477"]={town="rosewood",x=8027,y=11477,lx=8027,ly=11477,edge="N",street="Quiet St"}
S["8042,11605"]={town="rosewood",x=8042,y=11605,lx=8042,ly=11605,edge="W",street=""}
S["8046,11675"]={town="rosewood",x=8046,y=11675,lx=8046,ly=11675,edge="N",street=""}
S["8066,11626"]={town="rosewood",x=8066,y=11626,lx=8066,ly=11626,edge="N",street=""}
S["8068,11382"]={town="rosewood",x=8068,y=11382,lx=8068,ly=11382,edge="N",street="Snake St"}
S["8072,11580"]={town="rosewood",x=8072,y=11580,lx=8073,ly=11580,edge="W",street="Frederick Lane"}
S["8084,11477"]={town="rosewood",x=8084,y=11477,lx=8084,ly=11477,edge="W",street="Quiet St"}
S["8091,11576"]={town="rosewood",x=8091,y=11576,lx=8091,ly=11576,edge="N",street="Frederick Lane"}
S["8104,11461"]={town="rosewood",x=8104,y=11461,lx=8104,ly=11462,edge="N",street="North Main St"}
S["8104,11509"]={town="rosewood",x=8104,y=11509,lx=8104,ly=11510,edge="N",street="North Main St"}
S["8104,11554"]={town="rosewood",x=8104,y=11554,lx=8104,ly=11555,edge="N",street="North Main St"}
S["8104,11595"]={town="rosewood",x=8104,y=11595,lx=8104,ly=11596,edge="N",street="North Main St"}
S["8104,11683"]={town="rosewood",x=8104,y=11683,lx=8104,ly=11684,edge="N",street="North Main St"}
S["8104,11685"]={town="rosewood",x=8104,y=11685,lx=8104,ly=11686,edge="N",street="North Main St"}
S["8104,11743"]={town="rosewood",x=8104,y=11743,lx=8104,ly=11744,edge="N",street="North Main St"}
S["8108,11412"]={town="rosewood",x=8108,y=11412,lx=8108,ly=11412,edge="N",street="North Main St"}
S["8108,11629"]={town="rosewood",x=8108,y=11629,lx=8108,ly=11629,edge="N",street="North Main St"}
S["8126,11478"]={town="rosewood",x=8126,y=11478,lx=8126,ly=11478,edge="W",street="Quiet St"}
S["8136,11657"]={town="rosewood",x=8136,y=11657,lx=8136,ly=11658,edge="N",street="Buck St"}
S["8136,11691"]={town="rosewood",x=8136,y=11691,lx=8136,ly=11691,edge="W",street=""}
S["8144,11597"]={town="rosewood",x=8144,y=11597,lx=8144,ly=11598,edge="N",street="Mortimer St"}
S["8147,11632"]={town="rosewood",x=8147,y=11632,lx=8148,ly=11632,edge="W",street="Mortimer St"}
S["8153,11445"]={town="rosewood",x=8153,y=11445,lx=8153,ly=11445,edge="N",street=""}
S["8156,11408"]={town="rosewood",x=8156,y=11408,lx=8156,ly=11408,edge="W",street=""}
S["8167,11739"]={town="rosewood",x=8167,y=11739,lx=8167,ly=11739,edge="N",street=""}
S["8169,11739"]={town="rosewood",x=8169,y=11739,lx=8169,ly=11739,edge="N",street=""}
S["8196,11657"]={town="rosewood",x=8196,y=11657,lx=8196,ly=11658,edge="N",street="Buck St"}
S["8239,11657"]={town="rosewood",x=8239,y=11657,lx=8239,ly=11658,edge="N",street="Buck St"}
S["8249,11476"]={town="rosewood",x=8249,y=11476,lx=8249,ly=11476,edge="N",street="Quiet St"}
S["8259,11775"]={town="rosewood",x=8259,y=11775,lx=8259,ly=11775,edge="N",street="South Main St"}
S["8262,11576"]={town="rosewood",x=8262,y=11576,lx=8262,ly=11576,edge="W",street="Frederick Lane"}
S["8264,11589"]={town="rosewood",x=8264,y=11589,lx=8264,ly=11589,edge="W",street="Cartwheel St"}
S["8264,11638"]={town="rosewood",x=8264,y=11638,lx=8264,ly=11638,edge="W",street="Cartwheel St"}
S["8264,11696"]={town="rosewood",x=8264,y=11696,lx=8264,ly=11696,edge="W",street="Cartwheel St"}
S["8265,11402"]={town="rosewood",x=8265,y=11402,lx=8265,ly=11402,edge="N",street="Butterfly St"}
S["8265,11541"]={town="rosewood",x=8265,y=11541,lx=8265,ly=11541,edge="N",street="Butterfly St"}
S["8274,11801"]={town="rosewood",x=8274,y=11801,lx=8275,ly=11801,edge="W",street="Rosewood Road"}
S["8301,11680"]={town="rosewood",x=8301,y=11680,lx=8301,ly=11681,edge="N",street="Schoolhouse St"}
S["8304,11581"]={town="rosewood",x=8304,y=11581,lx=8304,ly=11581,edge="W",street="Frederick Lane"}
S["8309,11599"]={town="rosewood",x=8309,y=11599,lx=8309,ly=11599,edge="W",street="Frederick Lane"}
S["8309,11601"]={town="rosewood",x=8309,y=11601,lx=8309,ly=11601,edge="W",street=""}
S["8341,11778"]={town="rosewood",x=8341,y=11778,lx=8341,ly=11779,edge="N",street="St Martin's Road"}
S["8347,11680"]={town="rosewood",x=8347,y=11680,lx=8347,ly=11681,edge="N",street="Schoolhouse St"}
S["8354,11580"]={town="rosewood",x=8354,y=11580,lx=8354,ly=11581,edge="N",street="Frederick Lane"}
S["8359,11402"]={town="rosewood",x=8359,y=11402,lx=8359,ly=11402,edge="N",street=""}
S["8367,11703"]={town="rosewood",x=8367,y=11703,lx=8367,ly=11704,edge="N",street="St Martin's Road"}
S["8367,11745"]={town="rosewood",x=8367,y=11745,lx=8367,ly=11746,edge="N",street="St Martin's Road"}
S["8398,11581"]={town="rosewood",x=8398,y=11581,lx=8398,ly=11581,edge="W",street="Frederick Lane"}
S["8409,11921"]={town="rosewood",x=8409,y=11921,lx=8409,ly=11921,edge="N",street="Catkin St"}
S["8418,12012"]={town="rosewood",x=8418,y=12012,lx=8418,ly=12012,edge="N",street=""}
S["8451,11921"]={town="rosewood",x=8451,y=11921,lx=8451,ly=11921,edge="N",street=""}
S["8462,12013"]={town="rosewood",x=8462,y=12013,lx=8462,ly=12013,edge="N",street=""}
H[#H+1]={town="rosewood",kind="squat",x=8134,y=11478,w=7,h=6}
H[#H+1]={town="rosewood",kind="pump",x=8393,y=12036,w=8,h=6}
H[#H+1]={town="rosewood",kind="squat",x=8164,y=11975,w=6,h=5}
H[#H+1]={town="rosewood",kind="maintenance",x=8432,y=11672,w=6,h=6}
H[#H+1]={town="rosewood",kind="maintenance",x=8148,y=11641,w=7,h=5}
H[#H+1]={town="rosewood",kind="squat",x=7997,y=11605,w=7,h=6}
H[#H+1]={town="rosewood",kind="squat",x=8455,y=11581,w=6,h=4}
H[#H+1]={town="rosewood",kind="maintenance",x=8267,y=11402,w=6,h=5}
H[#H+1]={town="rosewood",kind="pump",x=8456,y=12014,w=8,h=5}
H[#H+1]={town="rosewood",kind="laststand",x=8199,y=11375,w=7,h=6}
H[#H+1]={town="rosewood",kind="laststand",x=7948,y=11772,w=8,h=4}
H[#H+1]={town="rosewood",kind="maintenance",x=7905,y=11425,w=5,h=4}
H[#H+1]={town="rosewood",kind="pump",x=8148,y=11590,w=8,h=4}
I.towns["riverside"] = { name = "Riverside", x0 = 5676, y0 = 5170, x1 = 6834, y1 = 5574, tw = 5, th = 2, chunks = 1106 }
S["5716,5401"]={town="riverside",x=5716,y=5401,lx=5716,ly=5402,edge="N",street="Rag Road"}
S["5755,5248"]={town="riverside",x=5755,y=5248,lx=5755,ly=5248,edge="N",street="Fern Road"}
S["5879,5402"]={town="riverside",x=5879,y=5402,lx=5879,ly=5402,edge="W",street="Rock Ridge Road"}
S["5933,5242"]={town="riverside",x=5933,y=5242,lx=5933,ly=5242,edge="N",street="Sandy Road"}
S["5965,5210"]={town="riverside",x=5965,y=5210,lx=5965,ly=5210,edge="N",street=""}
S["6050,5315"]={town="riverside",x=6050,y=5315,lx=6050,ly=5315,edge="N",street="Ark Lane"}
S["6055,5294"]={town="riverside",x=6055,y=5294,lx=6055,ly=5294,edge="W",street="W Main St"}
S["6068,5299"]={town="riverside",x=6068,y=5299,lx=6068,ly=5299,edge="W",street="W Main St"}
S["6073,5323"]={town="riverside",x=6073,y=5323,lx=6073,ly=5323,edge="N",street=""}
S["6089,5295"]={town="riverside",x=6089,y=5295,lx=6089,ly=5295,edge="W",street="W Main St"}
S["6117,5362"]={town="riverside",x=6117,y=5362,lx=6117,ly=5362,edge="N",street="Pine Ct"}
S["6132,5386"]={town="riverside",x=6132,y=5386,lx=6132,ly=5386,edge="N",street="Lincoln St"}
S["6164,5227"]={town="riverside",x=6164,y=5227,lx=6164,ly=5227,edge="N",street=""}
S["6177,5334"]={town="riverside",x=6177,y=5334,lx=6177,ly=5334,edge="N",street="Johannes Jr St"}
S["6185,5243"]={town="riverside",x=6185,y=5243,lx=6185,ly=5243,edge="N",street=""}
S["6244,5281"]={town="riverside",x=6244,y=5281,lx=6244,ly=5281,edge="N",street="W Main St"}
S["6251,5399"]={town="riverside",x=6251,y=5399,lx=6251,ly=5399,edge="N",street="Lincoln St"}
S["6265,5303"]={town="riverside",x=6265,y=5303,lx=6265,ly=5303,edge="W",street="W Main St"}
S["6282,5326"]={town="riverside",x=6282,y=5326,lx=6282,ly=5326,edge="N",street=""}
S["6295,5281"]={town="riverside",x=6295,y=5281,lx=6295,ly=5281,edge="N",street="W Main St"}
S["6306,5456"]={town="riverside",x=6306,y=5456,lx=6306,ly=5456,edge="N",street="Nixon Lane"}
S["6321,5280"]={town="riverside",x=6321,y=5280,lx=6321,ly=5280,edge="N",street="E Main St"}
S["6326,5399"]={town="riverside",x=6326,y=5399,lx=6326,ly=5399,edge="N",street="Lincoln St"}
S["6344,5332"]={town="riverside",x=6344,y=5332,lx=6344,ly=5332,edge="W",street=""}
S["6388,5224"]={town="riverside",x=6388,y=5224,lx=6388,ly=5225,edge="N",street="Maria Pl"}
S["6388,5280"]={town="riverside",x=6388,y=5280,lx=6388,ly=5280,edge="N",street="E Main St"}
S["6389,5534"]={town="riverside",x=6389,y=5534,lx=6389,ly=5534,edge="N",street="Kennedy St"}
S["6408,5249"]={town="riverside",x=6408,y=5249,lx=6408,ly=5249,edge="N",street=""}
S["6441,5249"]={town="riverside",x=6441,y=5249,lx=6441,ly=5249,edge="N",street=""}
S["6441,5252"]={town="riverside",x=6441,y=5252,lx=6441,ly=5252,edge="W",street=""}
S["6451,5261"]={town="riverside",x=6451,y=5261,lx=6451,ly=5261,edge="N",street=""}
S["6459,5366"]={town="riverside",x=6459,y=5366,lx=6459,ly=5366,edge="N",street="Rosewood St"}
S["6461,5235"]={town="riverside",x=6461,y=5235,lx=6461,ly=5235,edge="N",street="Maria Pl"}
S["6462,5224"]={town="riverside",x=6462,y=5224,lx=6462,ly=5225,edge="N",street="Maria Pl"}
S["6494,5280"]={town="riverside",x=6494,y=5280,lx=6494,ly=5280,edge="N",street="E Main St"}
S["6494,5325"]={town="riverside",x=6494,y=5325,lx=6494,ly=5325,edge="N",street=""}
S["6532,5298"]={town="riverside",x=6532,y=5298,lx=6533,ly=5298,edge="W",street="Station St"}
S["6532,5325"]={town="riverside",x=6532,y=5325,lx=6533,ly=5325,edge="W",street="Station St"}
S["6532,5387"]={town="riverside",x=6532,y=5387,lx=6533,ly=5387,edge="W",street="Station St"}
S["6533,5232"]={town="riverside",x=6533,y=5232,lx=6533,ly=5232,edge="N",street="Mary Ct"}
S["6569,5317"]={town="riverside",x=6569,y=5317,lx=6569,ly=5317,edge="N",street=""}
S["6606,5280"]={town="riverside",x=6606,y=5280,lx=6606,ly=5280,edge="N",street="E Main St"}
S["6794,5214"]={town="riverside",x=6794,y=5214,lx=6795,ly=5214,edge="W",street="Riverbreeze Lane"}
S["6794,5285"]={town="riverside",x=6794,y=5285,lx=6794,ly=5285,edge="N",street="E Main St"}
H[#H+1]={town="riverside",kind="maintenance",x=5976,y=5276,w=7,h=6}
H[#H+1]={town="riverside",kind="maintenance",x=6331,y=5286,w=8,h=4}
H[#H+1]={town="riverside",kind="squat",x=6514,y=5402,w=8,h=4}
H[#H+1]={town="riverside",kind="laststand",x=6389,y=5503,w=6,h=4}
H[#H+1]={town="riverside",kind="squat",x=6802,y=5286,w=5,h=5}
H[#H+1]={town="riverside",kind="laststand",x=6645,y=5441,w=7,h=5}
H[#H+1]={town="riverside",kind="laststand",x=6378,y=5359,w=8,h=6}
H[#H+1]={town="riverside",kind="squat",x=6727,y=5275,w=6,h=6}
H[#H+1]={town="riverside",kind="laststand",x=6677,y=5539,w=6,h=6}
I.towns["ekron"] = { name = "Ekron", x0 = 263, y0 = 9522, x1 = 886, y1 = 10024, tw = 3, th = 2, chunks = 721 }
S["303,9851"]={town="ekron",x=303,y=9851,lx=303,ly=9852,edge="N",street="Hutchins Dr"}
S["309,9811"]={town="ekron",x=309,y=9811,lx=309,ly=9811,edge="N",street="Hutchins Dr"}
S["384,9678"]={town="ekron",x=384,y=9678,lx=384,ly=9678,edge="N",street="Broad St"}
S["384,9865"]={town="ekron",x=384,y=9865,lx=384,ly=9866,edge="N",street="West Alley St"}
S["386,9709"]={town="ekron",x=386,y=9709,lx=386,ly=9709,edge="N",street="West Alley St"}
S["386,9771"]={town="ekron",x=386,y=9771,lx=386,ly=9771,edge="N",street="West Alley St"}
S["386,9896"]={town="ekron",x=386,y=9896,lx=386,ly=9896,edge="N",street="Haysville Road"}
S["387,9813"]={town="ekron",x=387,y=9813,lx=388,ly=9813,edge="W",street="West Alley St"}
S["424,9914"]={town="ekron",x=424,y=9914,lx=424,ly=9914,edge="W",street="Haysville Road"}
S["435,9677"]={town="ekron",x=435,y=9677,lx=435,ly=9677,edge="N",street="Broad St"}
S["436,9984"]={town="ekron",x=436,y=9984,lx=436,ly=9984,edge="N",street=""}
S["439,9895"]={town="ekron",x=439,y=9895,lx=439,ly=9895,edge="N",street="Haysville Road"}
S["449,9810"]={town="ekron",x=449,y=9810,lx=449,ly=9811,edge="N",street="Hutchins Dr"}
S["451,9841"]={town="ekron",x=451,y=9841,lx=451,ly=9842,edge="N",street="East Alley St"}
S["457,9909"]={town="ekron",x=457,y=9909,lx=457,ly=9909,edge="W",street="Haysville Road"}
S["474,9937"]={town="ekron",x=474,y=9937,lx=474,ly=9937,edge="N",street=""}
S["475,9678"]={town="ekron",x=475,y=9678,lx=475,ly=9678,edge="N",street="Broad St"}
S["494,9810"]={town="ekron",x=494,y=9810,lx=494,ly=9811,edge="N",street="Chism Dr"}
S["510,9873"]={town="ekron",x=510,y=9873,lx=510,ly=9873,edge="N",street=""}
S["511,9677"]={town="ekron",x=511,y=9677,lx=511,ly=9677,edge="N",street="Broad St"}
S["519,9896"]={town="ekron",x=519,y=9896,lx=519,ly=9897,edge="N",street="Haysville Road"}
S["539,9676"]={town="ekron",x=539,y=9676,lx=539,ly=9676,edge="N",street="Broad St"}
S["554,9897"]={town="ekron",x=554,y=9897,lx=554,ly=9897,edge="W",street="Haysville Road"}
S["563,9676"]={town="ekron",x=563,y=9676,lx=563,ly=9676,edge="N",street="Broad St"}
S["564,9892"]={town="ekron",x=564,y=9892,lx=564,ly=9892,edge="N",street="Haysville Road"}
S["595,9699"]={town="ekron",x=595,y=9699,lx=595,ly=9699,edge="W",street="Railway St"}
S["595,9762"]={town="ekron",x=595,y=9762,lx=595,ly=9762,edge="W",street="Railway St"}
S["595,9807"]={town="ekron",x=595,y=9807,lx=595,ly=9807,edge="N",street="Railway St"}
S["597,9859"]={town="ekron",x=597,y=9859,lx=598,ly=9859,edge="W",street="Railway St"}
S["648,9734"]={town="ekron",x=648,y=9734,lx=648,ly=9734,edge="N",street="Willie Dr"}
S["685,9867"]={town="ekron",x=685,y=9867,lx=685,ly=9867,edge="N",street=""}
S["705,9736"]={town="ekron",x=705,y=9736,lx=705,ly=9737,edge="N",street="Dry Alley"}
S["706,9562"]={town="ekron",x=706,y=9562,lx=706,ly=9562,edge="W",street="Reese Ave"}
S["706,9675"]={town="ekron",x=706,y=9675,lx=706,ly=9675,edge="N",street="Reese Ave"}
S["708,9810"]={town="ekron",x=708,y=9810,lx=708,ly=9810,edge="N",street="Reese Ave"}
S["739,9878"]={town="ekron",x=739,y=9878,lx=739,ly=9878,edge="N",street="Haysville Road"}
S["760,9747"]={town="ekron",x=760,y=9747,lx=760,ly=9748,edge="N",street="Berry Dr"}
S["791,9771"]={town="ekron",x=791,y=9771,lx=791,ly=9771,edge="W",street=""}
S["799,9860"]={town="ekron",x=799,y=9860,lx=799,ly=9860,edge="N",street=""}
S["837,9810"]={town="ekron",x=837,y=9810,lx=837,ly=9811,edge="N",street="Parkway Ave"}
S["846,9856"]={town="ekron",x=846,y=9856,lx=846,ly=9856,edge="N",street="Parkway Ave"}
H[#H+1]={town="ekron",kind="pump",x=709,y=9737,w=5,h=6}
H[#H+1]={town="ekron",kind="maintenance",x=388,y=9647,w=8,h=5}
H[#H+1]={town="ekron",kind="maintenance",x=675,y=9670,w=7,h=6}
H[#H+1]={town="ekron",kind="maintenance",x=776,y=9679,w=8,h=6}
H[#H+1]={town="ekron",kind="squat",x=589,y=9790,w=6,h=6}
H[#H+1]={town="ekron",kind="squat",x=312,y=9897,w=8,h=4}
H[#H+1]={town="ekron",kind="pump",x=470,y=9771,w=5,h=5}
H[#H+1]={town="ekron",kind="pump",x=380,y=9774,w=5,h=4}
I.towns["fallas_lake"] = { name = "Fallas Lake", x0 = 7065, y0 = 8111, x1 = 7438, y1 = 8570, tw = 2, th = 2, chunks = 404 }
S["7105,8256"]={town="fallas_lake",x=7105,y=8256,lx=7105,ly=8257,edge="N",street="Victoria St"}
S["7106,8342"]={town="fallas_lake",x=7106,y=8342,lx=7106,ly=8342,edge="W",street="Victoria St"}
S["7106,8386"]={town="fallas_lake",x=7106,y=8386,lx=7106,ly=8386,edge="W",street="Victoria St"}
S["7123,8455"]={town="fallas_lake",x=7123,y=8455,lx=7123,ly=8455,edge="W",street=""}
S["7128,8371"]={town="fallas_lake",x=7128,y=8371,lx=7128,ly=8371,edge="N",street="Victoria St"}
S["7149,8319"]={town="fallas_lake",x=7149,y=8319,lx=7149,ly=8320,edge="N",street="Casey Road"}
S["7152,8175"]={town="fallas_lake",x=7152,y=8175,lx=7152,ly=8175,edge="N",street="Broadway St"}
S["7154,8371"]={town="fallas_lake",x=7154,y=8371,lx=7154,ly=8371,edge="N",street="Victoria St"}
S["7160,8204"]={town="fallas_lake",x=7160,y=8204,lx=7160,ly=8204,edge="N",street="Broadway St"}
S["7188,8249"]={town="fallas_lake",x=7188,y=8249,lx=7188,ly=8250,edge="N",street="Broadway St"}
S["7191,8300"]={town="fallas_lake",x=7191,y=8300,lx=7192,ly=8300,edge="W",street="Broadway St"}
S["7192,8452"]={town="fallas_lake",x=7192,y=8452,lx=7192,ly=8452,edge="W",street="Brickmore Road"}
S["7212,8151"]={town="fallas_lake",x=7212,y=8151,lx=7212,ly=8151,edge="N",street="Railview Road"}
S["7214,8406"]={town="fallas_lake",x=7214,y=8406,lx=7215,ly=8406,edge="W",street="Brickmore Road"}
S["7232,8212"]={town="fallas_lake",x=7232,y=8212,lx=7232,ly=8212,edge="N",street=""}
S["7235,8313"]={town="fallas_lake",x=7235,y=8313,lx=7235,ly=8313,edge="N",street=""}
S["7266,8410"]={town="fallas_lake",x=7266,y=8410,lx=7266,ly=8410,edge="N",street="Goose Lane"}
S["7266,8530"]={town="fallas_lake",x=7266,y=8530,lx=7266,ly=8530,edge="N",street="Main St"}
S["7268,8344"]={town="fallas_lake",x=7268,y=8344,lx=7268,ly=8344,edge="N",street="Main St"}
S["7274,8270"]={town="fallas_lake",x=7274,y=8270,lx=7274,ly=8270,edge="N",street="Main St"}
S["7274,8460"]={town="fallas_lake",x=7274,y=8460,lx=7274,ly=8460,edge="N",street="Main St"}
S["7285,8207"]={town="fallas_lake",x=7285,y=8207,lx=7285,ly=8207,edge="N",street="Main St"}
S["7286,8156"]={town="fallas_lake",x=7286,y=8156,lx=7286,ly=8156,edge="W",street="Railview Road"}
S["7308,8282"]={town="fallas_lake",x=7308,y=8282,lx=7308,ly=8282,edge="W",street="Fallas Way"}
S["7309,8347"]={town="fallas_lake",x=7309,y=8347,lx=7309,ly=8347,edge="N",street=""}
S["7312,8187"]={town="fallas_lake",x=7312,y=8187,lx=7312,ly=8187,edge="N",street=""}
S["7316,8266"]={town="fallas_lake",x=7316,y=8266,lx=7316,ly=8266,edge="N",street="Fallas Way"}
S["7317,8393"]={town="fallas_lake",x=7317,y=8393,lx=7317,ly=8393,edge="W",street=""}
S["7385,8273"]={town="fallas_lake",x=7385,y=8273,lx=7385,ly=8273,edge="N",street="Fallas Way"}
S["7398,8373"]={town="fallas_lake",x=7398,y=8373,lx=7398,ly=8373,edge="N",street="Lakehead Dr"}
H[#H+1]={town="fallas_lake",kind="squat",x=7137,y=8164,w=6,h=5}
H[#H+1]={town="fallas_lake",kind="pump",x=7212,y=8320,w=6,h=4}
H[#H+1]={town="fallas_lake",kind="squat",x=7327,y=8156,w=6,h=5}
H[#H+1]={town="fallas_lake",kind="maintenance",x=7364,y=8149,w=8,h=4}
H[#H+1]={town="fallas_lake",kind="laststand",x=7279,y=8325,w=6,h=5}
H[#H+1]={town="fallas_lake",kind="laststand",x=7269,y=8481,w=7,h=5}
I.towns["louisville"] = { name = "Louisville", x0 = 12860, y0 = 2398, x1 = 13009, y1 = 2961, tw = 1, th = 3, chunks = 315 }
S["12900,2438"]={town="louisville",x=12900,y=2438,lx=12900,ly=2438,edge="N",street="Ulster St"}
S["12900,2540"]={town="louisville",x=12900,y=2540,lx=12900,ly=2540,edge="N",street="Ulster St"}
S["12900,2640"]={town="louisville",x=12900,y=2640,lx=12900,ly=2640,edge="N",street="Ulster St"}
S["12900,2698"]={town="louisville",x=12900,y=2698,lx=12900,ly=2698,edge="N",street="Ulster St"}
S["12934,2439"]={town="louisville",x=12934,y=2439,lx=12934,ly=2439,edge="N",street="Quarantine Lane"}
S["12934,2823"]={town="louisville",x=12934,y=2823,lx=12934,ly=2824,edge="N",street="Angel St"}
S["12934,2921"]={town="louisville",x=12934,y=2921,lx=12934,ly=2921,edge="W",street="Angel St"}
S["12937,2887"]={town="louisville",x=12937,y=2887,lx=12937,ly=2887,edge="N",street="Angel St"}
S["12969,2439"]={town="louisville",x=12969,y=2439,lx=12969,ly=2439,edge="N",street="Quarantine Lane"}
H[#H+1]={town="louisville",kind="maintenance",x=12892,y=2531,w=7,h=5}
H[#H+1]={town="louisville",kind="maintenance",x=12936,y=2491,w=5,h=4}
I.towns["muldraugh_2"] = { name = "Muldraugh", x0 = 11420, y0 = 8755, x1 = 11870, y1 = 8896, tw = 2, th = 1, chunks = 154 }
S["11460,8836"]={town="muldraugh_2",x=11460,y=8836,lx=11460,ly=8836,edge="W",street=""}
S["11482,8798"]={town="muldraugh_2",x=11482,y=8798,lx=11482,ly=8798,edge="N",street=""}
S["11526,8814"]={town="muldraugh_2",x=11526,y=8814,lx=11526,ly=8814,edge="N",street="Frank Road"}
S["11642,8856"]={town="muldraugh_2",x=11642,y=8856,lx=11642,ly=8856,edge="N",street=""}
S["11678,8804"]={town="muldraugh_2",x=11678,y=8804,lx=11678,ly=8804,edge="N",street="Forest View Lane"}
S["11761,8795"]={town="muldraugh_2",x=11761,y=8795,lx=11761,ly=8796,edge="N",street="Dixie Loop N St"}
S["11830,8848"]={town="muldraugh_2",x=11830,y=8848,lx=11830,ly=8848,edge="N",street="Dixie Loop S St"}
H[#H+1]={town="muldraugh_2",kind="maintenance",x=11533,y=8834,w=6,h=4}
I.towns["muldraugh_3"] = { name = "Muldraugh", x0 = 10274, y0 = 9197, x1 = 10397, y1 = 9461, tw = 1, th = 2, chunks = 45 }
S["10314,9421"]={town="muldraugh_3",x=10314,y=9421,lx=10314,ly=9421,edge="N",street=""}
S["10322,9383"]={town="muldraugh_3",x=10322,y=9383,lx=10322,ly=9383,edge="W",street=""}
S["10333,9283"]={town="muldraugh_3",x=10333,y=9283,lx=10334,ly=9283,edge="W",street=""}
S["10344,9341"]={town="muldraugh_3",x=10344,y=9341,lx=10344,ly=9341,edge="N",street=""}
S["10357,9237"]={town="muldraugh_3",x=10357,y=9237,lx=10357,ly=9237,edge="N",street=""}
H[#H+1]={town="muldraugh_3",kind="laststand",x=10320,y=9420,w=5,h=4}
I.towns["west_point_2"] = { name = "West Point", x0 = 11557, y0 = 8190, x1 = 11730, y1 = 8383, tw = 1, th = 1, chunks = 85 }
S["11597,8310"]={town="west_point_2",x=11597,y=8310,lx=11597,ly=8310,edge="N",street="Riverside Road"}
S["11602,8230"]={town="west_point_2",x=11602,y=8230,lx=11602,ly=8230,edge="N",street=""}
S["11688,8343"]={town="west_point_2",x=11688,y=8343,lx=11688,ly=8343,edge="W",street="Tioga Road"}
S["11690,8267"]={town="west_point_2",x=11690,y=8267,lx=11690,ly=8267,edge="N",street=""}
H[#H+1]={town="west_point_2",kind="maintenance",x=11661,y=8321,w=6,h=6}
I.towns["louisville_2"] = { name = "Louisville", x0 = 13165, y0 = 1863, x1 = 13400, y1 = 1944, tw = 1, th = 1, chunks = 81 }
S["13205,1903"]={town="louisville_2",x=13205,y=1903,lx=13205,ly=1903,edge="N",street="W Market St"}
S["13250,1903"]={town="louisville_2",x=13250,y=1903,lx=13250,ly=1903,edge="N",street="W Market St"}
S["13312,1903"]={town="louisville_2",x=13312,y=1903,lx=13312,ly=1903,edge="N",street="W Market St"}
S["13360,1904"]={town="louisville_2",x=13360,y=1904,lx=13360,ly=1904,edge="N",street="W Market St"}
H[#H+1]={town="louisville_2",kind="pump",x=13215,y=1906,w=7,h=5}
I.towns["brandenburg"] = { name = "Brandenburg", x0 = 3490, y0 = 6010, x1 = 3570, y1 = 6090, tw = 1, th = 1, chunks = 21 }
S["3530,6050"]={town="brandenburg",x=3530,y=6050,lx=3530,ly=6050,edge="N",street="KY-60"}
H[#H+1]={town="brandenburg",kind="maintenance",x=3516,y=6076,w=6,h=6}
I.towns["muldraugh_4"] = { name = "Muldraugh", x0 = 10027, y0 = 9752, x1 = 10107, y1 = 9832, tw = 1, th = 1, chunks = 28 }
S["10067,9792"]={town="muldraugh_4",x=10067,y=9792,lx=10067,ly=9793,edge="N",street="Old Mill Road"}
H[#H+1]={town="muldraugh_4",kind="pump",x=10066,y=9808,w=7,h=6}
I.towns["knox_county"] = { name = "Knox County", x0 = 10046, y0 = 6642, x1 = 10126, y1 = 6722, tw = 1, th = 1, chunks = 4 }
S["10086,6682"]={town="knox_county",x=10086,y=6682,lx=10086,ly=6682,edge="N",street=""}
H[#H+1]={town="knox_county",kind="pump",x=10084,y=6684,w=5,h=6}
I.towns["west_point_3"] = { name = "West Point", x0 = 10335, y0 = 7408, x1 = 10415, y1 = 7488, tw = 1, th = 1, chunks = 13 }
S["10375,7448"]={town="west_point_3",x=10375,y=7448,lx=10375,ly=7448,edge="N",street="Raccoon Road"}
H[#H+1]={town="west_point_3",kind="maintenance",x=10344,y=7454,w=5,h=6}
I.towns["knox_county_2"] = { name = "Knox County", x0 = 14993, y0 = 780, x1 = 15073, y1 = 860, tw = 1, th = 1, chunks = 4 }
S["15033,820"]={town="knox_county_2",x=15033,y=820,lx=15033,ly=820,edge="N",street=""}
H[#H+1]={town="knox_county_2",kind="pump",x=15031,y=814,w=5,h=5}
return I
