"""Breaks the mod on purpose, one guard at a time, and checks the tests notice.

    python tests/mutate.py

Each mutation is applied, **asserted to have changed the file** (a mutation
that does not apply proves nothing -- pz_trekship DEV_GUIDE), the flow tests
run, and the file is put back byte for byte in a `finally`. One at a time:
two runs at once would restore each other's mutations.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA = os.path.join(ROOT, "Sewars", "42", "media", "lua")

MUTATIONS = [
    # Digging and blasting (0.7, SEW_Mine).
    ("mine: needs a tool", "server/SEW/SEW_Mine.lua",
     '    if not Mi.tool(player) then return refuse(player, "tool") end\n', ""),
    ("mine: within reach", "server/SEW/SEW_Mine.lua",
     '    if not S.within(player, ax, ay, C.Reach) then return refuse(player, "reach") end\n', ""),
    ("mine: only below", "server/SEW/SEW_Mine.lua",
     '    if not S.below(player) then return refuse(player, "level") end\n    if not S.within(player, ax, ay',
     '    if not S.within(player, ax, ay'),
    ("mine: off with the sandbox", "server/SEW/SEW_Mine.lua",
     '    if Mi.level() < 2 then return refuse(player, "off") end\n', ""),
    ("mine: not into somebody else's", "server/SEW/SEW_Mine.lua",
     '    if B.foreign(sq) then return "foreign" end\n', ""),
    ("mine: a ladder's wall stays", "server/SEW/SEW_Mine.lua",
     "    if not SOFT[Mi.edgeCode(ax, ay, bx, by)] or ladderOn(ax, ay, bx, by) then return false end",
     "    if not SOFT[Mi.edgeCode(ax, ay, bx, by)] then return false end"),
    ("mine: the nest's walls stay", "server/SEW/SEW_Mine.lua",
     "local SOFT = { c = true, b = true, e = true }", "local SOFT = { c = true, b = true, e = true, z = true, x = true, y = true }"),
    ("mine: earth where rock is exposed", "server/SEW/SEW_Mine.lua",
     '                setEdge(p, d[1], d[2], nx, ny, "e")\n', ""),
    ("mine: the wall dug through comes down", "server/SEW/SEW_Mine.lua",
     '    for _, t in ipairs(through) do setEdge(p, t[1], t[2], t[3], t[4], ".") end\n', ""),
    ("mine: what is dug is recorded", "server/SEW/SEW_Mine.lua",
     "    for _, e in ipairs(p.order) do B.setRecord(e.x, e.y, e.rec) end\n", ""),
    ("mine: a pass reads what was dug", "server/SEW/SEW_Build.lua",
     '            rec = over[x .. "," .. y] or rec\n', ""),
    ("mine: a pass rebuilds what was dug where no town is", "server/SEW/SEW_Build.lua",
     '            if B.square(tonumber(x), tonumber(y), rec, false, false) == "unloaded" then return false end\n        end\n        B.state().built[key] = B.rev()',
     '        end\n        B.state().built[key] = B.rev()'),
    ("mine: a pass rebuilds what the generator never had", "server/SEW/SEW_Build.lua",
     '                if B.square(tonumber(x), tonumber(y), rec, false, false) == "unloaded" then return false end\n', ""),
    ("mine: dug chunks are revisited", "server/SEW/SEW_Build.lua",
     "            if (B.townOf(key) or B.state().dug[key]) and not B.isCurrent(key) then",
     "            if B.townOf(key) and not B.isCurrent(key) then"),
    ("mine: stones", "server/SEW/SEW_Mine.lua",
     '                    U.try("mine.stone", function() sq:SpawnWorldInventoryItem(C.Mine.stone, 0.0, 0.0, 0.0) end)\n', ""),
    ("mine: heard", "server/SEW/SEW_Mine.lua",
     '    U.try("mine.noise", function() addSound(player, ax, ay, C.Z, C.Mine.noise[1], C.Mine.noise[2]) end)\n', ""),
    ("mine: masonry", "server/SEW/SEW_Mine.lua",
     '    U.try("mine.xp", function() addXp(player, Perks.Masonry, C.Mine.xp) end)\n', ""),
    ("mine: told", "server/SEW/SEW_Mine.lua", '    Net.toClient(player, "mined", { what = what })\n', ""),
    ("mine: heavy work", "shared/SEW/SEW_Actions.lua",
     '    U.try("mine.work", function() self.character:setMetabolicTarget(Metabolics.HeavyWork) end)\n', ""),
    ("mine: a pick is quicker", "shared/SEW/SEW_Actions.lua",
     '        or C.Mine.ticks[tool or "hammer"]', '        or C.Mine.ticks.hammer'),
    ("mine: the action's parameter names", "shared/SEW/SEW_Actions.lua", "    o.dx = dx\n", "    o.ddx = dx\n"),
    ("mine: on the menu", "client/SEW/SEW_Client.lua",
     '    if S.below(playerObj) and not test then U.try("mineMenu", Client.mineMenu, playerObj, context) end\n', ""),
    ("mine: greyed without a tool", "client/SEW/SEW_Client.lua",
     "        top.notAvailable = true\n        local tip = ISWorldObjectContextMenu.addToolTip()\n        tip.description = getText(\"Tooltip_SEW_MineNoTool\")",
     "        local tip = ISWorldObjectContextMenu.addToolTip()\n        tip.description = getText(\"Tooltip_SEW_MineNoTool\")"),
    ("mine: a ladder's wall is not offered", "client/SEW/SEW_Client.lua",
     "        if ladderOn(edgeHolder, edgeNorth) then", "        if false then"),
    ("mine: a door is not a wall to knock through", "client/SEW/SEW_Client.lua",
     '            if not door then out[#out + 1] = { dir = d[1], dx = d[2], dy = d[3], kind = "break" } end',
     '            out[#out + 1] = { dir = d[1], dx = d[2], dy = d[3], kind = "break" }'),
    ("blast: only below", "server/SEW/SEW_Mine.lua", "    if z ~= C.Z then return false end\n", ""),
    ("blast: only what explodes", "server/SEW/SEW_Mine.lua", "    if range <= 0 then return false end\n", ""),
    ("blast: off with the sandbox", "server/SEW/SEW_Mine.lua",
     "    if Mi.level() < 3 then return 0 end\n", ""),
    ("blast: after the dust, not inside the engine's own explosion", "server/SEW/SEW_Mine.lua",
     "    Mi.pending[#Mi.pending + 1] = { x = sq:getX(), y = sq:getY(), at = ticks + C.Mine.blastDelay }",
     "    Mi.blast(sq:getX(), sq:getY())"),
    ("blast: the engine's event", "server/SEW/SEW_Mine.lua",
     'Events.OnThrowableExplode.Add(function(...) U.try("mine.explode", Mi.onExplode, ...) end)\n', ""),
    ("blast: walls inside the round come down", "server/SEW/SEW_Mine.lua",
     "                through[#through + 1] = { q[1], q[2], nx, ny }\n", ""),
    ("blast: felt", "server/SEW/SEW_Mine.lua",
     'Net.toClient(p, "mined", { what = "blast" }) end', "local _ = p end"),
    # Annotated maps to the temple and the nest (0.6, SEW_Maps).
    ("maps: made by the game's own stash system", "server/SEW/SEW_Maps.lua",
     "        StashSystem.doStashItem(stash, item)\n", ""),
    ("maps: in the game's loot", "server/SEW/SEW_Maps.lua",
     'Events.OnFillContainer.Add(function(...) U.try("maps.fill", M.onFill, ...) end)\n', ""),
    ("maps: only a plain map", "server/SEW/SEW_Maps.lua",
     "        if item and isPlainMap(item) and not U.try", "        if item and item.setStashMap and not U.try"),
    ("maps: never somebody else's annotated map", "server/SEW/SEW_Maps.lua",
     ' and not U.try("fill.stash", function() return item:getStashMap() end)\n', "\n"),
    ("maps: by the dice", "server/SEW/SEW_Maps.lua",
     "                and ZombRand(1000) < C.Maps.loot * 1000 then", "                and true then"),
    ("maps: off with the sandbox's", "server/SEW/SEW_Maps.lua",
     "    if not container or not M.allowed() then return 0 end", "    if not container then return 0 end"),
    ("maps: on the dead below only", "server/SEW/SEW_Maps.lua",
     '    if (U.try("z.z", function() return z:getZ() end) or 0) > -0.5 then return false end\n', ""),
    ("maps: on the dead by the dice", "server/SEW/SEW_Maps.lua",
     "    if ZombRand(1000) >= C.Maps.dead * 1000 then return false end\n", ""),
    ("maps: in a crate by the dice", "server/SEW/SEW_Maps.lua",
     "    if roll(1000) > C.Maps.crate * 1000 then return false end\n", ""),
    ("maps: one of each placed", "server/SEW/SEW_Story.lua",
     "            local map = SEW.Maps.make(SEW.Maps.WHICH[idx or 0])", "            local map = nil"),
    ("maps: the sheet that shows them", "client/SEW/SEW_MapSheets.lua",
     "        LootMaps.Init[m.stash] = Sheets.init(m.bounds)\n", ""),
    ("maps: the X on the trapdoor", "shared/StashDescriptions/SewarsStashDesc.lua",
     '    stash:addStamp("X", nil, T.tx, T.ty, RED[1], RED[2], RED[3])', '    stash:addStamp("X", nil, T.x, T.y, RED[1], RED[2], RED[3])'),
    ("maps: the X on the manhole", "shared/StashDescriptions/SewarsStashDesc.lua",
     '    stash:addStamp("X", nil, L.cx, L.cy, INK[1], INK[2], INK[3])', '    stash:addStamp("X", nil, L.hx, L.hy, INK[1], INK[2], INK[3])'),
    ("maps: not the engine's to hand out", "shared/StashDescriptions/SewarsStashDesc.lua",
     '    local stash = StashUtil.newStash(m.stash, "Map", C.Maps.never, "Stash_AnnotedMap")\n    -- The trapdoor',
     '    local stash = StashUtil.newStash(m.stash, "Map", m.item, "Stash_AnnotedMap")\n    -- The trapdoor'),
    # The warren: the dens dug off the nest (0.6).
    ("warren: caches put down", "server/SEW/SEW_Build.lua",
     "        for _, e in ipairs(T.warren[key] or {}) do B.furnish(e, seed) end\n", ""),
    ("warren: the dead in the dens", "server/SEW/SEW_Build.lua",
     "        for _, z in ipairs(T.warrenDead[key] or {}) do B.setPiece(key, z) end\n", ""),
    ("set pieces: the dead are owed, not lost", "server/SEW/SEW_Build.lua",
     '    if why == "near" then\n        local s = B.state()', '    if false then\n        local s = B.state()'),
    ("set pieces: the owed are put down", "server/SEW/SEW_Server.lua",
     '    U.try("settle", B.settle)\n', ""),
    ("set pieces: not while somebody is still near", "server/SEW/SEW_Build.lua",
     'if why == "near" then left[#left + 1] = z elseif n then made = made + 1 end', "if n then made = made + 1 end"),
    ("set pieces: the temple's are owed too", "server/SEW/SEW_Build.lua",
     "            if piece then B.setPiece(key, z) else", "            if false then B.setPiece(key, z) else"),
    ("warren: once", "server/SEW/SEW_Build.lua", "        s.warren[key] = B.rev()\n", ""),
    ("warren: reaches a save that has the nest", "server/SEW/SEW_Build.lua",
     "    if s.warren[key] == nil and T.warren and (T.warren[key] or T.warrenDead[key]) then",
     "    if first and T.warren and (T.warren[key] or T.warrenDead[key]) then"),
    ("warren: its candles lit", "client/SEW/SEW_Client.lua",
     "            if math.abs(lx - px) <= r and math.abs(ly - py) <= r then lamp(lx, ly, C.CaveLight) end\n", ""),
    ("warren: the dev trip to its first den", "client/SEW/SEW_Client.lua",
     '        if what == "warren" then x, y, note = Wn.dens[1], Wn.dens[2]', '        if false then x, y, note = Wn.dens[1], Wn.dens[2]'),
    # The temple of the rat cult (0.6, DESIGN.md 7d).
    ("temple: a trapdoor, not a cover", "server/SEW/SEW_Build.lua",
     "shaft.outfall and C.Sprites.outfall or shaft.trapdoor and C.Sprites.hatch or C.Sprites.cover",
     "shaft.outfall and C.Sprites.outfall or C.Sprites.cover"),
    ("temple: no lid on a trapdoor", "shared/SEW/SEW_Actions.lua",
     "    o.hatch = shaft ~= nil and (shaft.hatch ~= nil or shaft.trapdoor == true)\n",
     "    o.hatch = shaft ~= nil and shaft.hatch ~= nil\n"),
    ("temple: the trapdoor says what it is", "client/SEW/SEW_Client.lua",
     'getText((shaft and shaft.trapdoor) and "Tooltip_SEW_Trap" or "Tooltip_SEW_Hatch")', 'getText("Tooltip_SEW_Hatch")'),
    ("temple: the way back up", "client/SEW/SEW_Client.lua",
     '        local label = (where.hatch or where.trapdoor) and "ContextMenu_SEW_HatchUp"',
     '        local label = where.hatch and "ContextMenu_SEW_HatchUp"'),
    ("temple: no daylight through a trapdoor", "client/SEW/SEW_Client.lua",
     "        if not s.hatch and not s.trapdoor and math.abs(s.x - px) <= r", "        if not s.hatch and math.abs(s.x - px) <= r"),
    ("temple: lit", "client/SEW/SEW_Client.lua",
     "            if math.abs(lx - px) <= r and math.abs(ly - py) <= r then lamp(lx, ly, C.TempleLight) end\n", ""),
    ("temple: its floors", "server/SEW/SEW_Build.lua",
     "    h = function() return C.Sprites.floorTemple end,\n", ""),
    ("temple: the cult's breach is a breach", "server/SEW/SEW_Build.lua",
     'local BREACH = { o = "o", q = "q", O = "o", Q = "q" }', 'local BREACH = { o = "o", q = "q" }'),
    ("temple: pictures hung", "server/SEW/SEW_Build.lua",
     "            if sq then hang(sq, e[3]) end\n", ""),
    ("temple: pictures on their walls", "server/SEW/SEW_Build.lua",
     '        for _, k in ipairs({ "sigil", "burrow", "torch", "banner" }) do sets[#sets + 1] = Sp.cult[k] end\n', ""),
    ("temple: the triptych on its wall", "server/SEW/SEW_Build.lua",
     '        for _, v in ipairs(Sp.cult.mural) do overlayEdges[v] = "N" end\n', ""),
    ("temple: marks reach old chunks", "server/SEW/SEW_Build.lua",
     "    if s.hung[key] == nil and T.pictures and T.pictures[key] then",
     "    if first and T.pictures and T.pictures[key] then"),
    ("temple: marks recorded hung", "server/SEW/SEW_Build.lua", "        s.hung[key] = B.rev()\n", ""),
    ("temple: its dead turned to the slab", "server/SEW/SEW_Build.lua",
     'U.try("zombie.face", function() list:get(0):faceLocation(fx + 0.5, fy + 0.5) end)', "local _ = fx"),
    ("temple: the facing handed on", "server/SEW/SEW_Build.lua",
     "    local n, why = B.spawn(z[1], z[2], B.dress(z[3], z[1], z[2]), z[4], z[5])\n    if why == \"near\" then",
     "    local n, why = B.spawn(z[1], z[2], B.dress(z[3], z[1], z[2]))\n    if why == \"near\" then"),
    ("temple: rats run its hall", "server/SEW/SEW_Build.lua",
     '        if SEW.Nest then U.try("rats", SEW.Nest.rats, runs, cx, cy) end\n',
     '        if SEW.Nest then U.try("rats", SEW.Nest.rats, open, cx, cy) end\n'),
    ("temple: the hall's word", "client/SEW/SEW_Map.lua",
     '            U.note(U.try("player", getPlayer), getText("IGUI_SEW_TempleHall"), 230, 150, 90)\n', ""),
    ("temple: each breach in turn", "client/SEW/SEW_Client.lua",
     "            Client.devNext.breach = Client.devNext.breach % #T.breaches + 1\n",
     "            Client.devNext.breach = 1\n"),
    ("temple: a town's sewer shows that town's map", "client/SEW/SEW_Map.lua",
     "            if temple and tid == temple.town then under = tid else return tid end\n",
     "            do return tid end\n"),
    ("temple: the dev build starts by its trapdoor", "client/SEW/SEW_Client.lua",
     '    local T = C.DevStart == "temple" and SEW.Index and SEW.Index.temple\n', "    local T = nil\n"),
    # Sewer gas (0.5, DESIGN.md 7b).
    ("gas: the dose", "server/SEW/SEW_Gas.lua",
     "        if give > 0 then stats:add(CharacterStat.POISON, give) end\n", ""),
    ("gas: the cap", "server/SEW/SEW_Gas.lua",
     "local give = math.max(0, math.min(dose, cap - now))", "local give = dose"),
    ("gas: a mask keeps it out", "server/SEW/SEW_Gas.lua", "    if G.protected(p) then\n", "    if false then\n"),
    ("gas: the filter is used", "server/SEW/SEW_Gas.lua",
     "            call(function() it:drainGasMask(C.Gas.filterDrain) end)\n", ""),
    ("gas: the stat synced", "server/SEW/SEW_Gas.lua",
     'U.try("gas.sync", function() syncPlayerStats(p, C.Gas.syncMask) end)', "local _ = p"),
    ("gas: dressed once", "server/SEW/SEW_Build.lua", "        s.gas[key] = B.rev()\n", ""),
    ("gas: not while off", "server/SEW/SEW_Build.lua",
     "if s.gas[key] == nil and SEW.Gas and SEW.Gas.strength() > 1 and", "if s.gas[key] == nil and SEW.Gas and"),
    ("gas: placards hung", "server/SEW/SEW_Gas.lua",
     "        if sq and B.hang(sq, C.Sprites.gasSign[s[3]]) then n = n + 1 end\n", ""),
    ("gas: on the map", "server/SEW/SEW_Gas.lua", "            if i then SEW.Discovery.gas(p, i) end\n", ""),
    ("gas: the note", "server/SEW/SEW_Gas.lua",
     '            Net.toClient(p, "gas", { protected = G.protected(p) })\n', ""),
    ("gas: no nagging", "server/SEW/SEW_Gas.lua",
     "        if here and G.inside[name] ~= here then", "        if here then"),
    ("gas: a plan knows", "server/SEW/SEW_Story.lua",
     "            SEW.Discovery.gas(player, i)\n", ""),
    # Locked gates (0.5, DESIGN.md 7, Locked gates).
    ("gates: keyed", "server/SEW/SEW_Build.lua", "            door:setKeyId(key)\n", ""),
    ("gates: locked", "server/SEW/SEW_Build.lua", "            door:setLockedByKey(true)\n", ""),
    ("gates: made from the sprite", "server/SEW/SEW_Build.lua",
     "IsoDoor.new(getCell(), sq, getSprite(sprite), north)", "IsoDoor.new(getCell(), sq, sprite, north)"),
    ("gates: a grille, not a door", "server/SEW/SEW_Build.lua",
     "            elseif n == \"j\" then putDoor(sq, true, key)", "            elseif n == \"j\" then putDoor(sq, true)"),
    ("gates: frame kept on revision", "server/SEW/SEW_Build.lua",
     '    if n == "d" or n == "j" then want[C.Sprites.doorFrame.N] = true end\n'
     '    if w == "d" or w == "j" then want[C.Sprites.doorFrame.W] = true end\n',
     '    if n == "d" then want[C.Sprites.doorFrame.N] = true end\n'
     '    if w == "d" then want[C.Sprites.doorFrame.W] = true end\n'),
    ("gates: the key in the crate", "server/SEW/SEW_Build.lua",
     'for _, k in ipairs(T.keys and T.keys[key] or {}) do U.try("key", SEW.Keys.stock, k[1], k[2], tid) end', ""),
    ("gates: the key's id", "server/SEW/SEW_Keys.lua", '    U.try("key.id", function() item:setKeyId(t.key) end)\n', ""),
    ("gates: the key on the dead", "server/SEW/SEW_Keys.lua",
     'if key and U.try("z.key", function() inv:AddItem(key); return true end) then added[#added + 1] = "key" end',
     "local _ = key"),
    ("gates: only the county's dead", "server/SEW/SEW_Keys.lua",
     '    if U.try("z.outfit", function() return z:getOutfitName() end) ~= C.Gates.outfit then return nil end\n', ""),
    ("gates: only below", "server/SEW/SEW_Keys.lua",
     '    if (U.try("z.z", function() return z:getZ() end) or 0) > -0.5 then return nil end\n', ""),
    ("gates: the latch", "server/SEW/SEW_Keys.lua",
     '    if ticks % C.Gates.latchEvery == 0 then U.try("keys.latch", K.latch) end\n', ""),
    ("gates: latched only shut", "server/SEW/SEW_Keys.lua",
     "elseif not inside and not d:IsOpen() and not d:isLockedByKey() then",
     "elseif not inside and not d:isLockedByKey() then"),
    ("gates: latch only ours", "server/SEW/SEW_Keys.lua",
     'if instanceof(d, "IsoDoor") and U.isOurs(d) and', 'if instanceof(d, "IsoDoor") and'),
    ("gates: a handle on the inside", "server/SEW/SEW_Keys.lua",
     "                if inside and d:isLockedByKey() then", "                if false then"),
    ("gates: not latched on anyone", "server/SEW/SEW_Keys.lua",
     "                elseif not inside and not d:IsOpen() and not d:isLockedByKey() then",
     "                elseif not d:IsOpen() and not d:isLockedByKey() then"),
    ("only an animal is asked its type", "server/SEW/SEW_Nest.lua",
     '    if not instanceof(a, "IsoAnimal") then return false end\n', ""),
    ("dev trips go down only onto a built floor", "client/SEW/SEW_Client.lua",
     "        U.teleport(p, x, y, 0)\n        Client.vault(p)\n        return true",
     "        Client.devTravel = nil\n        U.teleport(p, x, y, C.Z)\n        return true"),
    ("no bite through a wall", "server/SEW/SEW_Nest.lua",
     "    if d <= C.Rous.reach and not walled then", "    if d <= C.Rous.reach then"),
    ("gates: latch sent", "server/SEW/SEW_Keys.lua",
     "                    if isServer() then d:syncIsoObject(false, 0, nil, nil) end\n", ""),
    # Storm-drain outfalls (0.5, DESIGN.md 7c).
    ("outfalls: the grate", "server/SEW/SEW_Build.lua",
     "    local sprite = shaft.outfall and C.Sprites.outfall or shaft.trapdoor",
     "    local sprite = shaft.trapdoor"),
    ("outfalls: a grate is a way down", "shared/SEW/SEW_Sewer.lua",
     "\n                          or U.findSprite(sq, C.Sprites.outfall) ~= nil)", ")"),
    ("outfalls: on the menu", "client/SEW/SEW_Client.lua",
     '    if shaft and shaft.outfall then return "outfall", sq end\n', ""),
    ("outfalls: the note", "server/SEW/SEW_Server.lua",
     'mode = "down",\n                                     hatch = shaft.hatch ~= nil or shaft.trapdoor == true,\n'
     '                                     outfall = shaft.outfall == true })',
     'mode = "down",\n                                     hatch = shaft.hatch ~= nil or shaft.trapdoor == true })'),
    ("outfalls: no lid", "shared/SEW/SEW_Actions.lua",
     "    o.outfall = shaft ~= nil and shaft.outfall == true\n", "    o.outfall = false\n"),
    ("outfalls: blue on the map", "client/SEW/SEW_Map.lua",
     "            if sh.outfall then\n                self:drawRect(sx - mk, sy - mk, mk * 2, mk * 2, 1, 0.22, 0.48, 0.74)",
     "            if false then\n                self:drawRect(sx - mk, sy - mk, mk * 2, mk * 2, 1, 0.22, 0.48, 0.74)"),
    # The rats and the nest (0.5).
    ("rats on the first build", "server/SEW/SEW_Build.lua",
     '        if SEW.Nest then U.try("rats", SEW.Nest.rats, runs, cx, cy) end\n', ""),
    ("rodents put down with the nest", "server/SEW/SEW_Build.lua",
     '        if nest > 0 and SEW.Nest then U.try("rous", SEW.Nest.lairChunk, key) end\n', ""),
    ("each rodent once", "server/SEW/SEW_Nest.lua",
     "if not st.rous[k] and math.floor(x / 8)", "if math.floor(x / 8)"),
    ("the gate waits for the last of them", "server/SEW/SEW_Nest.lua",
     'if which == "gate" and (not N.allSpawned() or #N.living(L.x, L.y, C.Rous.range) > 0) then',
     'if which == "gate" and not N.allSpawned() then'),
    ("the living are the living", "server/SEW/SEW_Nest.lua",
     'if a and isRous(a) and not U.try("rous.dead", function() return a:isDead() end) then',
     'if a and isRous(a) then'),
    ("a pull within reach", "server/SEW/SEW_Nest.lua",
     '        return refuse(player, "reach")\n', '        local _ = 0\n'),
    ("the bite", "server/SEW/SEW_Nest.lua", "            N.bite(a, p)\n", ""),
    ("walked by hand when the path fails", "server/SEW/SEW_Nest.lua",
     "            if h.lx and U.dist(ax, ay, h.lx, h.ly) < 0.5 then", "            if false then"),
    ("never through a wall", "server/SEW/SEW_Nest.lua",
     'if not U.floorOf(there) or U.try("blocked", function() return here:isBlockedTo(there) end) ~= false then',
     "if not U.floorOf(there) then"),
    ("rats in the middle of their square", "server/SEW/SEW_Nest.lua",
     "            N.place(a, x + 0.5, y + 0.5)\n", ""),
    ("the leash", "server/SEW/SEW_Nest.lua",
     '    if ticks % C.LeashEvery == 0 then U.try("leash", N.leash) end\n', ""),
    ("an open gate is a breach", "server/SEW/SEW_Build.lua",
     "    if GATE[n] then n = B.gateOpen(GATE[n].which) and GATE[n].open or GATE[n].shut end\n"
     "    if GATE[w] then w = B.gateOpen(GATE[w].which) and GATE[w].open or GATE[w].shut end\n",
     "    if GATE[n] then n = GATE[n].shut end\n    if GATE[w] then w = GATE[w].shut end\n"),
    ("the false wall on the menu", "client/SEW/SEW_Client.lua",
     '        if which then return "pry", which end\n', ""),
    ("the ROUS moves as a rat", "shared/SEW/SEW_Rats.lua", '    d.animset = "rat"\n', '    d.animset = "rous"\n'),
    ("the dev build starts by the nest", "client/SEW/SEW_Client.lua",
     '    local h = C.DevStart == "lair" and Client.devLairHatch()', "    local h = nil"),
    ("unwall on revision", "server/SEW/SEW_Build.lua",
     "    if not first then B.unwall(sq, walls, n, w, fix) end\n", ""),
    ("old sludge swapped", "server/SEW/SEW_Build.lua",
     'U.try("unsludge", function() sq:transmitRemoveItemFromSquare(o) end)', ""),
    ("breach knocked through", "server/SEW/SEW_Build.lua",
     "    if BREACH[n] then hang(sq, C.Sprites.breach[BREACH[n]].N) end\n"
     "    if BREACH[w] then hang(sq, C.Sprites.breach[BREACH[w]].W) end\n", ""),
    ("rock gives way to a cave", "server/SEW/SEW_Build.lua",
     'U.try("unrock", function() sq:transmitRemoveItemFromSquare(floor) end)', ""),
    ("hideout furnished", "server/SEW/SEW_Build.lua",
     "for _, e in ipairs(T.caveFurniture and T.caveFurniture[key] or {}) do B.furnish(e, seed) end", ""),
    ("caves recorded done", "server/SEW/SEW_Build.lua",
     "        s.caves[key] = B.rev()\n", ""),
    ("dev start only in the dev build", "client/SEW/SEW_Client.lua",
     "if not SEW.Dev or isClient() or not p then devStartAt = nil return false end",
     "if isClient() or not p then devStartAt = nil return false end"),
    ("dev start only for a new character", "client/SEW/SEW_Client.lua",
     "    if isNew(p) then devStartPlayer = p end", "    devStartPlayer = p"),
    ("hatch gate on the server", "server/SEW/SEW_Server.lua",
     'if shaft.hatch and B.hatch(shaft) ~= "open" then return refuse(player, "shut") end', ""),
    ("hatch basement check", "server/SEW/SEW_Build.lua",
     "        if sq and foreign(sq) then\n            s.hatches[key] = \"blocked\"",
     "        if false then\n            s.hatches[key] = \"blocked\""),
    ("hatch surface pass", "server/SEW/SEW_Server.lua",
     ' else U.try("hatches", Server.hatches, p) end', " end"),
    ("hatch on the menu", "client/SEW/SEW_Client.lua",
     'if h and S.shaftAt(h:getX(), h:getY()) then return "hatch", h end', ""),
    ("no rescue to a hatch", "shared/SEW/SEW_Sewer.lua",
     "        if not s.hatch then\n            local d = U.dist(x, y, s.x, s.y)",
     "        if true then\n            local d = U.dist(x, y, s.x, s.y)"),
    ("covers of ours go in", "server/SEW/SEW_Server.lua",
     "            elseif s.made and not st.covers[key] then B.cover(s) end", "            end"),
    ("cover gate on the server", "server/SEW/SEW_Server.lua",
     'if shaft.made and B.cover(shaft) ~= "placed" then return refuse(player, "shut") end', ""),
    ("a cover of ours is a cover", "shared/SEW/SEW_Sewer.lua",
     " or U.findSprite(sq, C.Sprites.cover) ~= nil\n", "\n"),
    ("only our old sludge", "server/SEW/SEW_Build.lua",
     "if U.isOurs(o) and U.spriteName(o) == C.Sprites.sludgeOld then", "if U.spriteName(o) == C.Sprites.sludgeOld then"),
    ("discovery", "server/SEW/SEW_Server.lua",
     'if S.below(p) then U.try("discover", SEW.Discovery.look, p) else', 'if S.below(p) then local _ = p else'),
    ("ladder on the map", "server/SEW/SEW_Server.lua",
     "        SEW.Discovery.ladder(player, x, y)\n        U.log(\"%s climbs down", "        U.log(\"%s climbs down"),
    ("map clip", "client/SEW/SEW_Map.lua",
     "self:setStencilRect(0, top, self.width, bottom - top)", ""),
    ("journals stocked", "server/SEW/SEW_Build.lua",
     "if extra and SEW.Story then SEW.Story.stockExtras(c, extra) end", ""),
    ("journal marks", "server/SEW/SEW_Story.lua",
     'return SEW.Discovery.mark(player, "j" .. idx, j.x, j.y, j.kind)', "return false"),
    ("plan reveals", "server/SEW/SEW_Story.lua",
     "local n = SEW.Discovery.reveal(player, plan.town, x0, y0, x0 + C.MapTile - 1, y0 + C.MapTile - 1)",
     "local n = 0"),
    ("fog cache", "client/SEW/SEW_Map.lua",
     "if cached and cached.v == M.version then return cached.rects end", "if cached then return cached.rects end"),
    ("no next in Kahlua", "client/SEW/SEW_Client.lua",
     "        if anyLamp() then Client.clearLamps() end", "        if next(lamps) then Client.clearLamps() end"),
    ("reach refusal", "server/SEW/SEW_Server.lua",
     'if not S.within(player, x, y, C.Reach + 1.0) then return refuse(player, "reach") end', ""),
    ("level refusal (up)", "server/SEW/SEW_Server.lua",
     '        if not S.below(player) then return refuse(player, "level") end\n        if not (S.within', '        if not (S.within'),
    ("grant before build", "server/SEW/SEW_Server.lua",
     "local done, left = B.around(x, y, C.EntryRadiusChunks)", "local done, left = 0, 0"),
    ("foreign squares", "server/SEW/SEW_Build.lua",
     'if fresh and foreign(sq) then return "foreign" end', ""),
    ("stock once", "server/SEW/SEW_Build.lua",
     "        s.first[key] = B.rev()\n", ""),
    # Set in one place only, B.furnish, for every container stocked or not: a
    # second copy in U.fill hid this mutation, and was taken out.
    ("explored", "server/SEW/SEW_Build.lua",
     '        U.try("explored", function() c:setExplored(true) end)\n', ""),
    ("map key off the engine", "client/SEW/SEW_Map.lua",
     'addKeyBind("sewerMapKey", getText("IGUI_SEW_MapKey"), Keyboard.KEY_K,',
     'addKeyBind("sewerMapKey", getText("IGUI_SEW_MapKey"), Keyboard.KEY_N,'),
    ("0.3.1's saved key", "client/SEW/SEW_Map.lua",
     'addKeyBind("sewerMapKey",', 'addKeyBind("sewerMap",'),
    ("map key at the wheel", "client/SEW/SEW_Map.lua",
     '    if U.try("map.vehicle", function() return p:getVehicle() end) then return end\n', ""),
    ("loot count", "shared/SEW/SEW_Util.lua",
     "    for _ = 1, count or 0 do", "    for _ = 1, #list do"),
    ("equipped share", "server/SEW/SEW_Build.lua",
     "if roll(100) <= C.EquippedShare[mix] * 100 then", "if roll(100) <= 36 then"),
    ("shelter dead undressed", "server/SEW/SEW_Build.lua",
     "    if not EQUIPPED[outfit] then return outfit end\n", "    do return outfit end\n"),
    ("pictures hang on walls", "server/SEW/SEW_Build.lua",
     "    if not host then return put(sq, sprite) end\n", "    do return put(sq, sprite) end\n"),
    ("hung pictures reach clients", "server/SEW/SEW_Build.lua",
     "        if isServer() then host:transmitUpdatedSpriteToClients() end\n", ""),
    ("old saves rehung", "server/SEW/SEW_Build.lua",
     "    if not first then B.rehang(sq) end\n", ""),
    ("spawn clearance", "server/SEW/SEW_Build.lua",
     'if nearAPlayer(x, y, C.SpawnClearance) then return false, "near" end', ""),
    ("door as special", "server/SEW/SEW_Build.lua",
     "if isServer() then door:transmitCompleteItemToClients() end", ""),
    ("vault off", "client/SEW/SEW_Client.lua",
     'U.try("vault.off", function() p:setIgnoreAutoVault(false) end)', ""),
    ("wait for the floor", "client/SEW/SEW_Client.lua",
     "    if not arrivable(m.x, m.y, m.z) then", "    if false then"),
    ("lamps down", "client/SEW/SEW_Client.lua",
     "        Client.clearLamps()\n    elseif m.mode == \"rescue\"", "    elseif m.mode == \"rescue\""),
    ("action parameter names", "shared/SEW/SEW_Actions.lua",
     "    o.x = x\n", "    o.cx = x\n"),
    ("rescue", "client/SEW/SEW_Client.lua",
     '    Net.send(p, "rescue", {})', ""),
    ("client guard", "client/SEW/SEW_Client.lua",
     "if isServer() then return end", ""),
    ("server guard", "server/SEW/SEW_Server.lua",
     "if isClient() then return end", ""),
    ("below is indoors", "shared/SEW/SEW_Compat.lua",
     "        if P.below(self) then return false end\n", ""),
    ("the street stays outside", "shared/SEW/SEW_Compat.lua",
     "return z ~= nil and z < 0", "return z ~= nil and z <= 0"),
    ("wrap the engine's method", "shared/SEW/SEW_Compat.lua",
     "local engine = rawget(index, ORIGINAL) or index.isOutside", "local engine = index.isOutside"),
    ("shut cover", "client/SEW/SEW_Client.lua",
     '    if shaft then return "down", sq end\n    return "shut", sq',
     '    return "down", sq'),
    # Below ground is not all ours (bunkers, basements, the base at -14).
    ("bunker: the sewer is one level", "shared/SEW/SEW_Sewer.lua",
     "    return z < C.Z + 0.5 and z >= C.Z - 0.5", "    return z < C.Z + 0.5"),
    ("bunker: the client leaves a deeper square", "client/SEW/SEW_Client.lua",
     'if sq and (U.try("sq.z", function() return sq:getZ() end) ~= C.Z or U.foreign(sq)) then return end',
     "if sq and U.foreign(sq) then return end"),
    ("bunker: the client leaves a basement's stairs", "client/SEW/SEW_Client.lua",
     " ~= C.Z or U.foreign(sq)) then return end", " ~= C.Z) then return end"),
    ("bunker: the server asks the level", "server/SEW/SEW_Server.lua",
     "    if not S.below(player) then return false end\n    local sq = U.try(\"square\"", "    local sq = U.try(\"square\""),
    ("bunker: the server leaves a deeper square", "server/SEW/SEW_Server.lua",
     'if U.try("sq.z", function() return sq:getZ() end) ~= C.Z or B.foreign(sq) then return false end',
     "if B.foreign(sq) then return false end"),
    ("bunker: the server leaves a basement's stairs", "server/SEW/SEW_Server.lua",
     " ~= C.Z or B.foreign(sq) then return false end", " ~= C.Z then return false end"),
    ("bunker: a bare square far from any sewer", "server/SEW/SEW_Server.lua",
     "    return false\nend\n\n--- A client below ground found no floor under its player.",
     "    return true\nend\n\n--- A client below ground found no floor under its player."),
    ("bunker: the rescue asks first", "server/SEW/SEW_Server.lua",
     "    if not Server.ours(player, px, py) then return end\n", ""),
    # The click (ISContextMenu.get slides the menu; requestX/Y is the click).
    ("click: where the click was", "shared/SEW/SEW_Util.lua",
     "    local sx, sy = context.requestX, context.requestY", "    local sx, sy = context.x, context.y"),
    ("click: the mouse when no click was kept", "shared/SEW/SEW_Util.lua",
     '        sx = U.try("getMouseX", function() return getMouseX() end)', "        sx = nil"),
    # The street does not hear the sewer (SEW_Street).
    ("street: only zombies on the street", "client/SEW/SEW_Street.lua",
     "    if z:getZ() < 0 or z:getPathTargetZ() ~= C.Z then return false end", "    if z:getPathTargetZ() ~= C.Z then return false end"),
    ("street: only a sound at the sewer's level", "client/SEW/SEW_Street.lua",
     "    if z:getZ() < 0 or z:getPathTargetZ() ~= C.Z then return false end", "    if z:getZ() < 0 then return false end"),
    ("street: only on its way to a player's sound", "client/SEW/SEW_Street.lua",
     "    if not z:isMovingToPlayerSound() then return false end\n", ""),
    ("street: only near somebody in the sewer", "client/SEW/SEW_Street.lua",
     "        if math.abs(p[1] - tx) <= r and math.abs(p[2] - ty) <= r then", "        if true then"),
    ("street: not another client's zombie", "client/SEW/SEW_Street.lua",
     "    if z:isRemoteZombie() then return false end\n", ""),
    ("street: the sandbox's Yes", "client/SEW/SEW_Street.lua",
     "    if not Street.hears() then", "    if true then"),
    ("street: only a square of ours", "client/SEW/SEW_Street.lua",
     "                if sq and ours(sq) then out", "                if sq then out"),
    ("street: only at the sewer's level", "client/SEW/SEW_Street.lua",
     "            if S.below(p) then\n                local sq = U.try(\"street.sq\"", "            if true then\n                local sq = U.try(\"street.sq\""),
    ("street: the path is dropped", "client/SEW/SEW_Street.lua",
     "            z:setPath2(nil)\n", ""),
    ("street: it stops pathing", "client/SEW/SEW_Street.lua",
     '            z:setVariable("bPathfind", false)\n', ""),
    ("street: it stops moving", "client/SEW/SEW_Street.lua",
     '            z:setVariable("bMoving", false)\n', ""),
    ("street: the look is kept up", "client/SEW/SEW_Street.lua",
     '    if tick % C.Street.every == 0 then U.try("street.look", Street.look) end', ""),
]


def main():
    missed = []
    # `python tests/mutate.py temple` runs only the mutations whose name has
    # that word in it: for the ones just written. Before a release, all of them.
    only = sys.argv[1] if len(sys.argv) > 1 else ""
    for name, rel, old, new in MUTATIONS:
        if only not in name:
            continue
        path = os.path.join(LUA, rel)
        orig = open(path, "rb").read()
        text = orig.decode("utf-8")
        if old not in text:
            print("  NOAPPLY  %s: the search text is not in %s" % (name, rel))
            missed.append(name)
            continue
        mutated = text.replace(old, new, 1)
        assert mutated != text
        try:
            open(path, "wb").write(mutated.encode("utf-8"))
            r = subprocess.run([sys.executable, os.path.join(ROOT, "tests", "test_flow.py")],
                               capture_output=True, text=True)
            caught = r.returncode != 0
            first = next((l.strip() for l in r.stdout.splitlines() if "FAIL" in l), r.stderr.strip()[-120:])
            print("  %s  %-24s %s" % ("caught" if caught else "MISSED", name, first if caught else ""))
            if not caught:
                missed.append(name)
        finally:
            open(path, "wb").write(orig)
        if open(path, "rb").read() != orig:
            sys.exit("could not restore " + rel)
    print()
    if missed:
        print("MISSED: %s" % ", ".join(missed))
        sys.exit(1)
    print("every mutation caught")


if __name__ == "__main__":
    main()
